<?php

    $codigo_arp = 14;
    // $periodo_pago_dif = '2015-01';
    // $periodo_pago = '2016-01';
    $num_empleados = 12;
    $valor_nomina = 120000;

    /*
    * Array de la configuracion de la resolucion 1747 de 2008 -> Articulo 7 REGISTRO TIPO 1 : ENCABEZADO
    * primer nivel es el numero del campo
    */
    $arrayEncabezado['1']  = array('long'=>2,   'posicion'=>array('ini' => 1,   'fin'=> 2),   'tipo' => 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=>' ', 'campo_bd'=>'',                               'value' => '01',   'descripcion' => 'Tipo de Registro' );
    $arrayEncabezado['2A'] = array('long'=>1,   'posicion'=>array('ini' => 3,   'fin'=> 3),   'tipo' => 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=>' ', 'campo_bd'=>'',                               'value' => '0',    'descripcion' => 'Modalidad de la planilla' );
    $arrayEncabezado['2B'] = array('long'=>4,   'posicion'=>array('ini' => 4,   'fin'=> 7),   'tipo' => 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=>' ', 'campo_bd'=>'',                               'value' => '0001', 'descripcion' => 'Secuencia' );
    $arrayEncabezado['3']  = array('long'=>200, 'posicion'=>array('ini' => 8,   'fin'=> 207), 'tipo' => 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=>' ', 'campo_bd'=>'terceros.nombre',                'value' => '',     'descripcion' => 'Nombre o razon social del aportante' );
    $arrayEncabezado['4']  = array('long'=>2,   'posicion'=>array('ini' => 208, 'fin'=> 209), 'tipo' => 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=>' ', 'campo_bd'=>'terceros.tipo_identificacion',   'value' => '',     'descripcion' => 'tipo documento del aportante' );
    $arrayEncabezado['5']  = array('long'=>16,  'posicion'=>array('ini' => 210, 'fin'=> 225), 'tipo' => 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=>' ', 'campo_bd'=>'terceros.numero_identificacion', 'value' => '',     'descripcion' => 'Numero de identificacion del aportante' );
    $arrayEncabezado['6']  = array('long'=>1,   'posicion'=>array('ini' => 226, 'fin'=> 226), 'tipo' => 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=>' ', 'campo_bd'=>'terceros.dv',                    'value' => '',     'descripcion' => 'Digito de Verificacion del aportante' );
    $arrayEncabezado['7']  = array('long'=>1,   'posicion'=>array('ini' => 227, 'fin'=> 227), 'tipo' => 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=>' ', 'campo_bd'=>'',                               'value' => 'E',    'descripcion' => 'Tipo de planilla' );
    $arrayEncabezado['8']  = array('long'=>10,  'posicion'=>array('ini' => 228, 'fin'=> 237), 'tipo' => 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=>'0', 'campo_bd'=>'',                               'value' => '',     'descripcion' => 'Numero de la planilla asociada a esta planilla' );
    $arrayEncabezado['9']  = array('long'=>10,  'posicion'=>array('ini' => 238, 'fin'=> 247), 'tipo' => 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=>'0', 'campo_bd'=>'',                               'value' => '',     'descripcion' => 'Fecha de pago planilla sociada a esta planilla AAAA-MM-DD' );
    $arrayEncabezado['10'] = array('long'=>1,   'posicion'=>array('ini' => 248, 'fin'=> 248), 'tipo' => 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=>' ', 'campo_bd'=>'',                               'value' => 'U',    'descripcion' => 'Forma de presentacion' );
    $arrayEncabezado['11'] = array('long'=>10,  'posicion'=>array('ini' => 249, 'fin'=> 258), 'tipo' => 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=>' ', 'campo_bd'=>'',                               'value' => '',     'descripcion' => 'Codigo de la sucursal del aportante' );
    $arrayEncabezado['12'] = array('long'=>40,  'posicion'=>array('ini' => 259, 'fin'=> 298), 'tipo' => 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=>' ', 'campo_bd'=>'',                               'value' => '',     'descripcion' => 'Nombre de la sucursal' );
    $arrayEncabezado['13'] = array('long'=>6,   'posicion'=>array('ini' => 299, 'fin'=> 304), 'tipo' => 'A', 'aling'=>STR_PAD_LEFT,  'rellena_espacios'=>' ', 'campo_bd'=>'configuracion_arl.codigo_arl',   'value' => "",      'descripcion' => 'Codigo de la ARP  a la cual el aportante se encuentra afiliado' );
    $arrayEncabezado['14'] = array('long'=>7,   'posicion'=>array('ini' => 305, 'fin'=> 311), 'tipo' => 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=>' ', 'campo_bd'=>'',                               'value' => "$periodo_pago_dif",'descripcion' => 'Periodo de pago para los sistemas diferentes al de salud' );
    $arrayEncabezado['15'] = array('long'=>7,   'posicion'=>array('ini' => 312, 'fin'=> 318), 'tipo' => 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=>' ', 'campo_bd'=>'',                               'value' => "$periodo_pago",    'descripcion' => 'Periodo de pago  para el sistema de salud' );
    $arrayEncabezado['16'] = array('long'=>10,  'posicion'=>array('ini' => 319, 'fin'=> 328), 'tipo' => 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=>'0', 'campo_bd'=>'',                               'value' => '',     'descripcion' => 'Numero de radicacion o de la planilla integrada de liquidacion de aportes' );
    $arrayEncabezado['17'] = array('long'=>10,  'posicion'=>array('ini' => 329, 'fin'=> 338), 'tipo' => 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=>' ', 'campo_bd'=>'',                               'value' => '',     'descripcion' => 'Fecha de pago aaaa-mm-dd' );
    $arrayEncabezado['18'] = array('long'=>5,   'posicion'=>array('ini' => 339, 'fin'=> 343), 'tipo' => 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=>'0', 'campo_bd'=>'',                               'value' => "$num_empleados",     'descripcion' => 'Numero total de empleados' );
    $arrayEncabezado['19'] = array('long'=>12,  'posicion'=>array('ini' => 344, 'fin'=> 355), 'tipo' => 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=>'0', 'campo_bd'=>'',                               'value' => "$valor_nomina",     'descripcion' => 'Valor total de la nomina' );
    $arrayEncabezado['20'] = array('long'=>1,   'posicion'=>array('ini' => 356, 'fin'=> 356), 'tipo' => 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=>' ', 'campo_bd'=>'',                               'value' => '1',     'descripcion' => 'Tipo de aportante' );
    $arrayEncabezado['21'] = array('long'=>2,   'posicion'=>array('ini' => 357, 'fin'=> 358), 'tipo' => 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=>'0', 'campo_bd'=>'',                               'value' => '',     'descripcion' => 'Codigo del operador de informacion' );

    $dias_pension                       = 30;
    $dias_salud                         = 30;
    $dias_ARL                           = 30;
    $dias_CCF                           = 30;
    $salario_basico                     = 684000;
    $salario_integral                   = 0;
    $IBC_pension                        = 684000;
    $IBC_salud                          = 684000;
    $IBC_ARL                            = 684000;
    $IBC_CCF                            = 684000;

    /*
    * Array de la configuracion de la resolucion 1747 de 2008 -> Articulo 10 DESCRIPCION DETALLADA DE LAS VARIABLES DE NOVEDADES GENERALES (REGISTRO TIPO 2)
    * primer nivel es el numero del campo
    */
    $arrayRegistroTipo2['1']  = array('long'=> 2,  'posicion'=>array('ini'=> 1,'fin'=> 2),     'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"02",                                       'descripcion'=>'Tipo de Registro' );
    $arrayRegistroTipo2['2']  = array('long'=> 5,  'posicion'=>array('ini'=> 3,'fin'=> 7),     'tipo'=> 'N', 'aling'=>STR_PAD_LEFT,  'rellena_espacios'=> '0', 'campo_bd'=>'', 'value'=>"",                                         'descripcion'=>'Secuencia' );
    $arrayRegistroTipo2['3']  = array('long'=> 2,  'posicion'=>array('ini'=> 8,'fin'=> 8),     'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'empleados.tipo_documento_nombre', 'value'=>"",          'descripcion'=>'Tipo documento del cotizante' );
    $arrayRegistroTipo2['4']  = array('long'=> 16, 'posicion'=>array('ini'=> 10,'fin'=> 25),   'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'empleados.documento', 'value'=>"",                      'descripcion'=>'Numero de identificación del cotizante' );
    $arrayRegistroTipo2['5']  = array('long'=> 2,  'posicion'=>array('ini'=> 26,'fin'=> 27),   'tipo'=> 'N', 'aling'=>STR_PAD_LEFT,  'rellena_espacios'=> '0', 'campo_bd'=>'empleados.tipo_cotizante', 'value'=>"01",               'descripcion'=>'Tipo cotizante' );
    $arrayRegistroTipo2['6']  = array('long'=> 2,  'posicion'=>array('ini'=> 28,'fin'=> 29),   'tipo'=> 'N', 'aling'=>STR_PAD_LEFT,  'rellena_espacios'=> '0', 'campo_bd'=>'empleados.subtipo_cotizante', 'value'=>"00",            'descripcion'=>'Subtipo de cotizante' );
    $arrayRegistroTipo2['7']  = array('long'=> 1,  'posicion'=>array('ini'=> 30,'fin'=> 30),   'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'empleados.extranjero_obligado_cotizar', 'value'=>"",    'descripcion'=>'Extranjero no obligado a cotizar a pensiones' );
    $arrayRegistroTipo2['8']  = array('long'=> 1,  'posicion'=>array('ini'=> 31,'fin'=> 31),   'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'empleados.residente_en_exterior', 'value'=>"",          'descripcion'=>'Colombiano residente en el exterior' );
    $arrayRegistroTipo2['9']  = array('long'=> 2,  'posicion'=>array('ini'=> 32,'fin'=> 33),   'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'empleados.codigo_departamento_laboral', 'value'=>"",    'descripcion'=>'Código del Departamento de la ubicación laboral' );
    $arrayRegistroTipo2['10'] = array('long'=> 3,  'posicion'=>array('ini'=> 34,'fin'=> 36),   'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'empleados.codigo_municipio_laboral', 'value'=>"",       'descripcion'=>'Código del Municipio de ubicación laboral' );
    $arrayRegistroTipo2['11'] = array('long'=> 20, 'posicion'=>array('ini'=> 37,'fin'=> 56),   'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'empleados.apellido1', 'value'=>"",                      'descripcion'=>'Primer apellido' );
    $arrayRegistroTipo2['12'] = array('long'=> 30, 'posicion'=>array('ini'=> 57,'fin'=> 86),   'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'empleados.apellido2', 'value'=>"",                      'descripcion'=>'Segundo apellido' );
    $arrayRegistroTipo2['13'] = array('long'=> 20, 'posicion'=>array('ini'=> 87,'fin'=> 106),  'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'empleados.nombre1', 'value'=>"",                        'descripcion'=>'Primer nombre' );
    $arrayRegistroTipo2['14'] = array('long'=> 30, 'posicion'=>array('ini'=> 107,'fin'=> 136), 'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'empleados.nombre2', 'value'=>"",                        'descripcion'=>'Segundo nombre' );
    $arrayRegistroTipo2['15'] = array('long'=> 1,  'posicion'=>array('ini'=> 137,'fin'=> 137), 'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"",                                         'descripcion'=>'ING: Ingreso' );
    $arrayRegistroTipo2['16'] = array('long'=> 1,  'posicion'=>array('ini'=> 138,'fin'=> 138), 'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"",                                         'descripcion'=>'RET: Retiro' );
    $arrayRegistroTipo2['17'] = array('long'=> 1,  'posicion'=>array('ini'=> 139,'fin'=> 139), 'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"",                                         'descripcion'=>'TDE: Traslado desde otra EPS ó EOC' );
    $arrayRegistroTipo2['18'] = array('long'=> 1,  'posicion'=>array('ini'=> 140,'fin'=> 140), 'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"",                                         'descripcion'=>'TAE: Traslado a otra EPS o EOC' );
    $arrayRegistroTipo2['19'] = array('long'=> 1,  'posicion'=>array('ini'=> 141,'fin'=> 141), 'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"",                                         'descripcion'=>'TDP: Traslado desde otra Administradora de Pensiones' );
    $arrayRegistroTipo2['20'] = array('long'=> 1,  'posicion'=>array('ini'=> 142,'fin'=> 142), 'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"",                                         'descripcion'=>'TAP: Traslado a otra Administradora de Pensiones' );
    $arrayRegistroTipo2['21'] = array('long'=> 1,  'posicion'=>array('ini'=> 143,'fin'=> 143), 'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"",                                         'descripcion'=>'VSP: Variación permanente de salario' );
    $arrayRegistroTipo2['22'] = array('long'=> 1,  'posicion'=>array('ini'=> 144,'fin'=> 144), 'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"",                                         'descripcion'=>'Correcciones' );
    $arrayRegistroTipo2['23'] = array('long'=> 1,  'posicion'=>array('ini'=> 145,'fin'=> 145), 'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"",                                         'descripcion'=>'VST: Variación transitoria del salario' );
    $arrayRegistroTipo2['24'] = array('long'=> 1,  'posicion'=>array('ini'=> 146,'fin'=> 146), 'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"",                                         'descripcion'=>'SLN: Suspensión temporal del contrato de trabajo o licencia no remunerada o comisión de servicios' );
    $arrayRegistroTipo2['25'] = array('long'=> 1,  'posicion'=>array('ini'=> 147,'fin'=> 147), 'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"",                                         'descripcion'=>'IGE: Incapacidad Temporal por Enfermedad General.' );
    $arrayRegistroTipo2['26'] = array('long'=> 1,  'posicion'=>array('ini'=> 148,'fin'=> 148), 'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"",                                         'descripcion'=>'LMA: Licencia de Maternidad o de paternidad' );
    $arrayRegistroTipo2['27'] = array('long'=> 1,  'posicion'=>array('ini'=> 149,'fin'=> 149), 'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"",                                         'descripcion'=>'VAC: Vacaciones' );
    $arrayRegistroTipo2['28'] = array('long'=> 1,  'posicion'=>array('ini'=> 150,'fin'=> 150), 'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"",                                         'descripcion'=>'AVP: Aporte Voluntario' );
    $arrayRegistroTipo2['29'] = array('long'=> 1,  'posicion'=>array('ini'=> 151,'fin'=> 151), 'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"",                                         'descripcion'=>'VCT: Variación centros de trabajo' );
    $arrayRegistroTipo2['30'] = array('long'=> 2,  'posicion'=>array('ini'=> 152,'fin'=> 153), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> '0', 'campo_bd'=>'', 'value'=>"",                                         'descripcion'=>'IRP: Incapacidad por accidente de trabajo o enfermedad profesional' );
    $arrayRegistroTipo2['31'] = array('long'=> 6,  'posicion'=>array('ini'=> 154,'fin'=> 159), 'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> '0', 'campo_bd'=>'empleados.codigo_administradora_pensiones', 'value'=>"",'descripcion'=>'Código de la Administradora de Pensiones a la cual pertenece el afiliado' );
    $arrayRegistroTipo2['32'] = array('long'=> 6,  'posicion'=>array('ini'=> 160,'fin'=> 165), 'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"",                                         'descripcion'=>'Código de la Administradora de Pensiones a la cual se traslada el afiliado' );
    $arrayRegistroTipo2['33'] = array('long'=> 6,  'posicion'=>array('ini'=> 166,'fin'=> 171), 'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'empleados.campo_EPS_EOC', 'value'=>"",                  'descripcion'=>'Código EPS o EOC a la cual pertenece el afiliado' );
    $arrayRegistroTipo2['34'] = array('long'=> 6,  'posicion'=>array('ini'=> 172,'fin'=> 177), 'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"",                                         'descripcion'=>'Código EPS o EOC a la cual se traslada el afiliado' );
    $arrayRegistroTipo2['35'] = array('long'=> 6,  'posicion'=>array('ini'=> 178,'fin'=> 183), 'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'empleados.codigo_CCF', 'value'=>"",                     'descripcion'=>'Código CCF a la pertenece el afiliado' );
    $arrayRegistroTipo2['36'] = array('long'=> 2,  'posicion'=>array('ini'=> 184,'fin'=> 185), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"$dias_pension",                            'descripcion'=>'Número de días cotizados a Pensión' );
    $arrayRegistroTipo2['37'] = array('long'=> 2,  'posicion'=>array('ini'=> 186,'fin'=> 187), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"$dias_salud",                              'descripcion'=>'Número de días cotizados a Salud' );
    $arrayRegistroTipo2['38'] = array('long'=> 2,  'posicion'=>array('ini'=> 188,'fin'=> 189), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"$dias_ARL",                                'descripcion'=>'Número de días cotizados a Riesgos Profesionales' );
    $arrayRegistroTipo2['39'] = array('long'=> 2,  'posicion'=>array('ini'=> 190,'fin'=> 191), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"$dias_CCF",                                'descripcion'=>'Número de días cotizados a Cajas de Compensación' );
    $arrayRegistroTipo2['40'] = array('long'=> 9,  'posicion'=>array('ini'=> 192,'fin'=> 200), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"$salario_basico",                          'descripcion'=>'Salario básico (sin centavos)' );
    $arrayRegistroTipo2['41'] = array('long'=> 1,  'posicion'=>array('ini'=> 201,'fin'=> 201), 'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"$salario_integral",                        'descripcion'=>'Salario integral ' );
    $arrayRegistroTipo2['42'] = array('long'=> 9,  'posicion'=>array('ini'=> 202,'fin'=> 210), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"$IBC_pension",                             'descripcion'=>'IBC Pensión' );
    $arrayRegistroTipo2['43'] = array('long'=> 9,  'posicion'=>array('ini'=> 211,'fin'=> 219), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"$IBC_salud",                               'descripcion'=>'IBC Salud ' );
    $arrayRegistroTipo2['44'] = array('long'=> 9,  'posicion'=>array('ini'=> 220,'fin'=> 228), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"$IBC_ARL",                                 'descripcion'=>'IBC Riesgos Profesionales' );
    $arrayRegistroTipo2['45'] = array('long'=> 9,  'posicion'=>array('ini'=> 229,'fin'=> 237), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"$IBC_CCF",                                 'descripcion'=>'IBC CCF' );


    $arrayRegistroTipo4['1']  = array('long'=> 2,  'posicion'=>array('ini'=> 1,'fin'=> 2),     'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"04", 'descripcion'=>'Tipo de Registro' );
    $arrayRegistroTipo4['2']  = array('long'=> 5,  'posicion'=>array('ini'=> 3,'fin'=> 7),     'tipo'=> 'N', 'aling'=>STR_PAD_LEFT, 'rellena_espacios'=> '0',  'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Secuencia' );
    $arrayRegistroTipo4['3']  = array('long'=> 6,  'posicion'=>array('ini'=> 8,'fin'=> 13),    'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'empleados.campo_EPS_EOC', 'value'=>"", 'descripcion'=>'Codigo Administradora de Salud' );
    $arrayRegistroTipo4['4']  = array('long'=> 16, 'posicion'=>array('ini'=> 14,'fin'=> 29),   'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Numero de identificacion (NIT) de la EPS o EOC' );
    $arrayRegistroTipo4['5']  = array('long'=> 1,  'posicion'=>array('ini'=> 30,'fin'=> 30),   'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Digito de verificacion de la EPS o EOC' );
    $arrayRegistroTipo4['6']  = array('long'=> 10, 'posicion'=>array('ini'=> 31,'fin'=> 40),   'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Valor total cotizaciones obligatorias aportadas a esa administradora' );
    $arrayRegistroTipo4['7']  = array('long'=> 10, 'posicion'=>array('ini'=> 41,'fin'=> 50),   'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Valor total UPC adicionales aportadas a esa administradora' );
    $arrayRegistroTipo4['8']  = array('long'=> 15, 'posicion'=>array('ini'=> 51,'fin'=> 65),   'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Numero de la autorizacion de pago de las incapacidades' );
    $arrayRegistroTipo4['9']  = array('long'=> 10, 'posicion'=>array('ini'=> 66,'fin'=> 75),   'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Valor total de las incapacidades pagadas' );
    $arrayRegistroTipo4['10'] = array('long'=> 15, 'posicion'=>array('ini'=> 76,'fin'=> 90),   'tipo'=> 'A', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Numero de autorizaciones de descuento de licencias de maternidad' );
    $arrayRegistroTipo4['11'] = array('long'=> 10, 'posicion'=>array('ini'=> 91,'fin'=> 100),  'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Valor total de las licencias de maternidad o paternidad pagadas' );
    $arrayRegistroTipo4['12'] = array('long'=> 10, 'posicion'=>array('ini'=> 101,'fin'=> 110), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Valor neto aportes cotizacion' );
    $arrayRegistroTipo4['13'] = array('long'=> 4,  'posicion'=>array('ini'=> 111,'fin'=> 114), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Numero de dias de mora liquidados' );
    $arrayRegistroTipo4['14'] = array('long'=> 10, 'posicion'=>array('ini'=> 115,'fin'=> 124), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Valor intereses de mora, cotizaciones obligatorias' );
    $arrayRegistroTipo4['15'] = array('long'=> 10, 'posicion'=>array('ini'=> 125,'fin'=> 134), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Valor intereses de mora, UPC adicionales' );
    $arrayRegistroTipo4['16'] = array('long'=> 10, 'posicion'=>array('ini'=> 135,'fin'=> 144), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Subtotal aportes cotizacion' );
    $arrayRegistroTipo4['17'] = array('long'=> 10, 'posicion'=>array('ini'=> 145,'fin'=> 154), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Subtotal aportes UPC adicionales' );
    $arrayRegistroTipo4['18'] = array('long'=> 10, 'posicion'=>array('ini'=> 155,'fin'=> 164), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'N. del formulario unico o planilla integrada inicial objeto de saldo a favor del empleador' );
    $arrayRegistroTipo4['19'] = array('long'=> 10, 'posicion'=>array('ini'=> 165,'fin'=> 174), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Valor del saldo a favor del periodo anterior correspondiente a la cotizacion obligatoria' );
    $arrayRegistroTipo4['20'] = array('long'=> 10, 'posicion'=>array('ini'=> 175,'fin'=> 184), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Valor del saldo a favor del periodo anterior de la UPC adicional' );
    $arrayRegistroTipo4['21'] = array('long'=> 10, 'posicion'=>array('ini'=> 185,'fin'=> 194), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Total a pagar por cotizacion obligatoria' );
    $arrayRegistroTipo4['22'] = array('long'=> 10, 'posicion'=>array('ini'=> 195,'fin'=> 204), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Total a pagar por UPC adicional' );
    $arrayRegistroTipo4['23'] = array('long'=> 10, 'posicion'=>array('ini'=> 205,'fin'=> 214), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Total a pagar a la administradora' );
    $arrayRegistroTipo4['24'] = array('long'=> 10, 'posicion'=>array('ini'=> 215,'fin'=> 224), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Valor fondo de solidaridad y garantia FOSYGA' );
    $arrayRegistroTipo4['25'] = array('long'=> 6,  'posicion'=>array('ini'=> 225,'fin'=> 230), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Total afiliados por administradora' );

    $arrayRegistroTipo5['1']  = array('long'=> 2,  'posicion'=>array('ini'=> 1,'fin'=> 2),     'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Tipo registro' );
    $arrayRegistroTipo5['2']  = array('long'=> 5,  'posicion'=>array('ini'=> 3,'fin'=> 7),     'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Secuencia' );
    $arrayRegistroTipo5['3']  = array('long'=> 6,  'posicion'=>array('ini'=> 8,'fin'=> 13),    'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Codigo ARP' );
    $arrayRegistroTipo5['4']  = array('long'=> 16, 'posicion'=>array('ini'=> 14,'fin'=> 29),   'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Numero de identificacion (NIT) de la ARP' );
    $arrayRegistroTipo5['5']  = array('long'=> 1,  'posicion'=>array('ini'=> 30,'fin'=> 30),   'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Digito de verificacion de la ARP' );
    $arrayRegistroTipo5['6']  = array('long'=> 10, 'posicion'=>array('ini'=> 31,'fin'=> 40),   'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Valor total cotizaciones reportadas a esa administradora' );
    $arrayRegistroTipo5['7']  = array('long'=> 15, 'posicion'=>array('ini'=> 41,'fin'=> 55),   'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Numero de autorizacion de pago de las incapacidades' );
    $arrayRegistroTipo5['8']  = array('long'=> 10, 'posicion'=>array('ini'=> 56,'fin'=> 65),   'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Valor total de las incapacidades pagadas' );
    $arrayRegistroTipo5['9']  = array('long'=> 10, 'posicion'=>array('ini'=> 66,'fin'=> 75),   'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Valor aportes pagados a otros sistemas' );
    $arrayRegistroTipo5['10'] = array('long'=> 10, 'posicion'=>array('ini'=> 76,'fin'=> 85),   'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Valor neto aportes cotizacion' );
    $arrayRegistroTipo5['11'] = array('long'=> 4,  'posicion'=>array('ini'=> 86,'fin'=> 89),   'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Numero de dias de mora liquidados' );
    $arrayRegistroTipo5['12'] = array('long'=> 10, 'posicion'=>array('ini'=> 90,'fin'=> 99),   'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Valor interes de mora sobre las cotizaciones obligatorias' );
    $arrayRegistroTipo5['13'] = array('long'=> 10, 'posicion'=>array('ini'=> 100,'fin'=> 109), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'subtotal aportes cotizacion' );
    $arrayRegistroTipo5['14'] = array('long'=> 10, 'posicion'=>array('ini'=> 110,'fin'=> 119), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'N. formulario unico o planilla integrada inicial objeto de saldo a favor del empleador' );
    $arrayRegistroTipo5['15'] = array('long'=> 10, 'posicion'=>array('ini'=> 120,'fin'=> 129), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Valor del saldo a favor del periodo anterior' );
    $arrayRegistroTipo5['16'] = array('long'=> 10, 'posicion'=>array('ini'=> 130,'fin'=> 139), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'TOTAL A PAGAR A LA ADMINISTRADORA' );
    $arrayRegistroTipo5['17'] = array('long'=> 10, 'posicion'=>array('ini'=> 140,'fin'=> 149), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Fondo de riessgos profesionales' );
    $arrayRegistroTipo5['18'] = array('long'=> 6,  'posicion'=>array('ini'=> 150,'fin'=> 155), 'tipo'=> 'N', 'aling'=>STR_PAD_RIGHT, 'rellena_espacios'=> ' ', 'campo_bd'=>'', 'value'=>"", 'descripcion'=>'Total afiliados por administradora' );
?>