<?php

	$sqlPucNiif = "INSERT INTO puc_niif (id_empresa,cuenta,descripcion,grupo_empresarial)
					VALUES
					('$id_empresa', 1, 'ACTIVO','$idGrupoEmpresarial'),
					('$id_empresa', 11, 'EFECTIVO Y EQUIVALENTES AL EFECTIVO','$idGrupoEmpresarial'),
					('$id_empresa', 1105, 'CAJA','$idGrupoEmpresarial'),
					('$id_empresa', 110505, 'CAJA GENERAL','$idGrupoEmpresarial'),
					('$id_empresa', 110510, 'CAJAS MENORES','$idGrupoEmpresarial'),
					('$id_empresa', 1110, 'BANCOS','$idGrupoEmpresarial'),
					('$id_empresa', 111005, 'MONEDA NACIONAL','$idGrupoEmpresarial'),
					('$id_empresa', 111010, 'MONEDA EXTRANJERA','$idGrupoEmpresarial'),
					('$id_empresa', 12, 'ACTIVOS FINANCIEROS','$idGrupoEmpresarial'),
					('$id_empresa', 1205, 'ACTIVOS FINANCIEROS (INVERSIONES EN ACCIONES)','$idGrupoEmpresarial'),
					('$id_empresa', 120520, 'INDUSTRIA MANUFACTURERA','$idGrupoEmpresarial'),
					('$id_empresa', 13, 'DEUDORES COMERCIALES Y OTRAS CUENTAS POR COBRAR','$idGrupoEmpresarial'),
					('$id_empresa', 1305, 'DEUDORES COMERCIALES','$idGrupoEmpresarial'),
					('$id_empresa', 130505, 'DEUDORES COMERCIALES NACIONALES','$idGrupoEmpresarial'),
					('$id_empresa', 130510, 'DEUDORES COMERCIALES DEL EXTERIOR','$idGrupoEmpresarial'),
					('$id_empresa', 1310, 'CUENTAS CORRIENTES COMERCIALES','$idGrupoEmpresarial'),
					('$id_empresa', 131020, 'PARTICULARES','$idGrupoEmpresarial'),
					('$id_empresa', 131095, 'OTRAS','$idGrupoEmpresarial'),
					('$id_empresa', 1315, 'CUENTAS POR COBRAR A CASA MATRIZ','$idGrupoEmpresarial'),
					('$id_empresa', 1320, 'CUENTAS POR COBRAR A VINCULADOS ECONOMICOS','$idGrupoEmpresarial'),
					('$id_empresa', 1323, 'CUENTAS POR COBRAR A DIRECTORES','$idGrupoEmpresarial'),
					('$id_empresa', 1325, 'CUENTAS POR COBRAR A SOCIOS Y ACCIONISTA','$idGrupoEmpresarial'),
					('$id_empresa', 132505, 'A SOCIOS','$idGrupoEmpresarial'),
					('$id_empresa', 132510, 'A ACCIONISTAS','$idGrupoEmpresarial'),
					('$id_empresa', 1328, 'APORTES POR COBRAR','$idGrupoEmpresarial'),
					('$id_empresa', 1330, 'ANTICIPOS Y AVANCES','$idGrupoEmpresarial'),
					('$id_empresa', 133005, 'A PROVEEDORES','$idGrupoEmpresarial'),
					('$id_empresa', 133006, 'PROVEEDORES DEL EXTERIOR','$idGrupoEmpresarial'),
					('$id_empresa', 133010, 'A CONTRATISTAS','$idGrupoEmpresarial'),
					('$id_empresa', 133015, 'A TRABAJADORES','$idGrupoEmpresarial'),
					('$id_empresa', 133020, 'A AGENTES','$idGrupoEmpresarial'),
					('$id_empresa', 1332, 'CUENTAS DE OPERACION CONJUNTA','$idGrupoEmpresarial'),
					('$id_empresa', 1335, 'DEPOSITOS','$idGrupoEmpresarial'),
					('$id_empresa', 133535, 'EN GARANTIA','$idGrupoEmpresarial'),
					('$id_empresa', 1340, 'PROMESAS DE COMPRA VENTA','$idGrupoEmpresarial'),
					('$id_empresa', 134015, 'DE FLOTA Y EQUIPO DE TRANSPORTE','$idGrupoEmpresarial'),
					('$id_empresa', 1345, 'INGRESOS POR COBRAR','$idGrupoEmpresarial'),
					('$id_empresa', 134505, 'DIVIDENDOS Y/O PARTICIPACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 134595, 'POR REMISIONES NO FACTURADAS','$idGrupoEmpresarial'),
					('$id_empresa', 1350, 'RECLAMACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 135005, 'A CAMPANIAS ASEGURADORAS','$idGrupoEmpresarial'),
					('$id_empresa', 1355, 'CUENTAS POR COBRAR A TRABAJADORES','$idGrupoEmpresarial'),
					('$id_empresa', 135595, 'OTROS','$idGrupoEmpresarial'),
					('$id_empresa', 1360, 'PRESTAMOS A PARTICULARES','$idGrupoEmpresarial'),
					('$id_empresa', 1360, 'DEUDORES VARIOS','$idGrupoEmpresarial'),
					('$id_empresa', 137095, 'INCAPACIDADES','$idGrupoEmpresarial'),
					('$id_empresa', 1375, 'DERECHOS DE RECOMPRA DE CARTERA NEGOCIADA','$idGrupoEmpresarial'),
					('$id_empresa', 1380, 'DEUDAS DE DIFICIL COBRO','$idGrupoEmpresarial'),
					('$id_empresa', 138010, 'CLIENTES EN PROCESO JURIDICO','$idGrupoEmpresarial'),
					('$id_empresa', 1389, 'PROVISIONES','$idGrupoEmpresarial'),
					('$id_empresa', 138905, 'CLIENTES','$idGrupoEmpresarial'),
					('$id_empresa', 138932, 'ANTICIPOS Y AVANCES','$idGrupoEmpresarial'),
					('$id_empresa', 14, 'INVENTARIOS','$idGrupoEmpresarial'),
					('$id_empresa', 1405, 'MATERIAS PRIMAS','$idGrupoEmpresarial'),
					('$id_empresa', 140510, 'COMPRA MATERIAS PRIMAS','$idGrupoEmpresarial'),
					('$id_empresa', 140590, 'SALDOS INICIALES MIGRACION','$idGrupoEmpresarial'),
					('$id_empresa', 140599, 'AJUSTES POR INFLACION','$idGrupoEmpresarial'),
					('$id_empresa', 1410, 'PRODUCTOS EN PROCESO','$idGrupoEmpresarial'),
					('$id_empresa', 141001, 'PROCESO DE FABRICACION','$idGrupoEmpresarial'),
					('$id_empresa', 141090, 'SALDOS INCIALES MIGRACION','$idGrupoEmpresarial'),
					('$id_empresa', 141099, 'AJUSTES POR INFLACION','$idGrupoEmpresarial'),
					('$id_empresa', 1415, 'OBRAS DE CONSTRUCION EN CURSO','$idGrupoEmpresarial'),
					('$id_empresa', 1417, 'OBRAS DE URBANISMO','$idGrupoEmpresarial'),
					('$id_empresa', 1420, 'CONTRATOS EN EJECUCION','$idGrupoEmpresarial'),
					('$id_empresa', 1425, 'CULTIVOS EN DESARROLLO','$idGrupoEmpresarial'),
					('$id_empresa', 1428, 'PLANTACIONES AGRICOLAS','$idGrupoEmpresarial'),
					('$id_empresa', 1430, 'PRODUCTOS TERMINADOS','$idGrupoEmpresarial'),
					('$id_empresa', 143005, 'PRODUCTOS MANUFACTURADOS','$idGrupoEmpresarial'),
					('$id_empresa', 143099, 'AJUSTES POR INFLACION','$idGrupoEmpresarial'),
					('$id_empresa', 1435, 'MERCANCIAS NO FABRICADAS POR LA EMPRESA','$idGrupoEmpresarial'),
					('$id_empresa', 143501, 'MERCANCIAS NO FABRICADAS POR LA EMPRESA','$idGrupoEmpresarial'),
					('$id_empresa', 1440, 'BIENES RAICES PARA LA VENTA','$idGrupoEmpresarial'),
					('$id_empresa', 144001, 'APARTAMENTOS','$idGrupoEmpresarial'),
					('$id_empresa', 144099, 'AJUSTES POR INFLACION','$idGrupoEmpresarial'),
					('$id_empresa', 1450, 'TERRENOS','$idGrupoEmpresarial'),
					('$id_empresa', 1455, 'MATERIALES, REPUESTOS Y ACCESORIOS','$idGrupoEmpresarial'),
					('$id_empresa', 145501, 'MATERIALES, REPUESTOS, SUMINISTROS','$idGrupoEmpresarial'),
					('$id_empresa', 145505, 'MATERIALES, REPUESTOS Y ACCESORIOS','$idGrupoEmpresarial'),
					('$id_empresa', 145590, 'SALDOS INCIALES MIGRACION','$idGrupoEmpresarial'),
					('$id_empresa', 145599, 'AJUSTES POR INFLACION','$idGrupoEmpresarial'),
					('$id_empresa', 1460, 'ENVASES Y EMPAQUES','$idGrupoEmpresarial'),
					('$id_empresa', 146005, 'ENVASES Y EMPAQUES','$idGrupoEmpresarial'),
					('$id_empresa', 146090, 'SALDOS INCIALES MIGRACION','$idGrupoEmpresarial'),
					('$id_empresa', 146099, 'AJUSTES POR INFLACION','$idGrupoEmpresarial'),
					('$id_empresa', 1465, 'INVENTARIOS EN TRANSITO','$idGrupoEmpresarial'),
					('$id_empresa', 146505, 'IMPORTACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 1499, 'PROVISIONES','$idGrupoEmpresarial'),
					('$id_empresa', 15, 'PROPIEDADES, PLANTA Y EQUIPO','$idGrupoEmpresarial'),
					('$id_empresa', 1504, 'TERRENOS','$idGrupoEmpresarial'),
					('$id_empresa', 150405, 'URBANOS','$idGrupoEmpresarial'),
					('$id_empresa', 150410, 'RURALES','$idGrupoEmpresarial'),
					('$id_empresa', 150499, 'AJUSTES POR INFLACION','$idGrupoEmpresarial'),
					('$id_empresa', 1506, 'MATERIALES PROYECTOS PETROLEROS','$idGrupoEmpresarial'),
					('$id_empresa', 1508, 'CONSTRUCIONES EN CURSO','$idGrupoEmpresarial'),
					('$id_empresa', 1512, 'MAQUINARIA Y EQUIPOS EN MONTAJE','$idGrupoEmpresarial'),
					('$id_empresa', 1516, 'CONSTRUCCIONES Y EDIFICACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 151605, 'EDIFICIOS','$idGrupoEmpresarial'),
					('$id_empresa', 151610, 'OFICINAS','$idGrupoEmpresarial'),
					('$id_empresa', 151670, 'PARQUEADEROS, GARAJES Y DEPOSITOS','$idGrupoEmpresarial'),
					('$id_empresa', 151680, 'BODEGAS','$idGrupoEmpresarial'),
					('$id_empresa', 151699, 'AJUSTES POR INFLACION','$idGrupoEmpresarial'),
					('$id_empresa', 1520, 'MAQUINARIA Y EQUIPO','$idGrupoEmpresarial'),
					('$id_empresa', 152010, 'MAQUINARIA','$idGrupoEmpresarial'),
					('$id_empresa', 152099, 'AJUSTES POR INFLACION','$idGrupoEmpresarial'),
					('$id_empresa', 1524, 'EQUIPO DE OFICINA','$idGrupoEmpresarial'),
					('$id_empresa', 152410, 'EQUIPOS','$idGrupoEmpresarial'),
					('$id_empresa', 152499, 'AJUSTES POR INFLACION','$idGrupoEmpresarial'),
					('$id_empresa', 1528, 'EQUIPO DE COMPUTACION Y COMUNICACION','$idGrupoEmpresarial'),
					('$id_empresa', 152805, 'EQUIPOS DE PROCESAMIENTO DE DATOS','$idGrupoEmpresarial'),
					('$id_empresa', 152810, 'EQUIPOS DE TELECOMUNICACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 152815, 'EQUIPOS DE RADIO','$idGrupoEmpresarial'),
					('$id_empresa', 152895, 'AJUSTES POR INFLACION','$idGrupoEmpresarial'),
					('$id_empresa', 152899, 'AJUSTES POR INFLACION','$idGrupoEmpresarial'),
					('$id_empresa', 1532, 'EQUIPO MEDICO-CIENTIFICO','$idGrupoEmpresarial'),
					('$id_empresa', 153215, 'LABORATORIO','$idGrupoEmpresarial'),
					('$id_empresa', 153299, 'AJUSTES POR INFLACION','$idGrupoEmpresarial'),
					('$id_empresa', 1536, 'EQUIPOS DE HOTELES Y RESTAURANTE','$idGrupoEmpresarial'),
					('$id_empresa', 1540, 'FLOTA Y EQUIPO DE TRANSPORTE','$idGrupoEmpresarial'),
					('$id_empresa', 154005, 'AUTOS, CAMIONETAS Y CAMPEROS','$idGrupoEmpresarial'),
					('$id_empresa', 154008, 'CAMIONES, VOLQUETAS Y FURGONES','$idGrupoEmpresarial'),
					('$id_empresa', 154099, 'AJUSTES POR INFLACION','$idGrupoEmpresarial'),
					('$id_empresa', 1544, 'FLOTA Y EQUIPO FLUVIAL Y/O MARITIMO','$idGrupoEmpresarial'),
					('$id_empresa', 1548, 'FLOTA Y EQUIPO AEREO','$idGrupoEmpresarial'),
					('$id_empresa', 1552, 'FLOTA Y EQUIPO FERREO','$idGrupoEmpresarial'),
					('$id_empresa', 1556, 'ACUEDUCTOS, PLANTAS Y REDES','$idGrupoEmpresarial'),
					('$id_empresa', 1560, 'ARMAMENTO DE VIGILANCIA','$idGrupoEmpresarial'),
					('$id_empresa', 1562, 'ENVASES Y EMPAQUES','$idGrupoEmpresarial'),
					('$id_empresa', 1564, 'PLANTACIONES AGRICOLAS Y FORESTALES','$idGrupoEmpresarial'),
					('$id_empresa', 1568, 'VIAS DE COMUNICACION','$idGrupoEmpresarial'),
					('$id_empresa', 1572, 'MINAS Y CANTERAS','$idGrupoEmpresarial'),
					('$id_empresa', 1576, 'POZOS ARTESIANOS','$idGrupoEmpresarial'),
					('$id_empresa', 1580, 'YACIMIENTOS','$idGrupoEmpresarial'),
					('$id_empresa', 1584, 'SEMOVIENTES','$idGrupoEmpresarial'),
					('$id_empresa', 1588, 'PROPIEDAD PLANTA Y EQUIPO EN TRANSITO','$idGrupoEmpresarial'),
					('$id_empresa', 158802, 'URBANOS','$idGrupoEmpresarial'),
					('$id_empresa', 158803, 'RURALES','$idGrupoEmpresarial'),
					('$id_empresa', 158804, 'CONSTRUCCIONES Y EDIFICACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 158805, 'MAQUINARIA Y EQUIPO','$idGrupoEmpresarial'),
					('$id_empresa', 158810, 'EQUIPO DE OFICINA','$idGrupoEmpresarial'),
					('$id_empresa', 158815, 'EQUIPO DE COMPUTACION Y COMUNICACION','$idGrupoEmpresarial'),
					('$id_empresa', 158820, 'EQUIPO MEDICO CIENTIFICO','$idGrupoEmpresarial'),
					('$id_empresa', 158825, 'CONSTRUCCIONES Y EDIFICACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 158830, 'FLOTA Y EQUIPO DE TRANSPORTE','$idGrupoEmpresarial'),
					('$id_empresa', 158835, 'LICENCIAS','$idGrupoEmpresarial'),
					('$id_empresa', 1592, 'DEPRECIACION ACUMULADA','$idGrupoEmpresarial'),
					('$id_empresa', 159205, 'CONSTRUCCIONES Y EDIFICACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 159206, 'CONSTRUCCIONES Y EDIFICACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 159210, 'MAQUINARIA Y EQUIPO','$idGrupoEmpresarial'),
					('$id_empresa', 159215, 'EQUIPO DE OFICINA','$idGrupoEmpresarial'),
					('$id_empresa', 159220, 'EQUIPO DE COMPUTACION Y COMUNICACION','$idGrupoEmpresarial'),
					('$id_empresa', 159225, 'LABORATORIO','$idGrupoEmpresarial'),
					('$id_empresa', 159235, 'FLOTA Y EQUIPO DE TRANSPORTE','$idGrupoEmpresarial'),
					('$id_empresa', 159236, 'FLOTA Y EQUIPO DE TRANSPORTE','$idGrupoEmpresarial'),
					('$id_empresa', 159288, 'DEPRECIACION ACTIVOS MENOR CUANTIA','$idGrupoEmpresarial'),
					('$id_empresa', 159290, 'SALDOS DE MIGRACION Ajustes','$idGrupoEmpresarial'),
					('$id_empresa', 159299, 'AJUSTES POR INFLACION','$idGrupoEmpresarial'),
					('$id_empresa', 1596, 'DEPRECIACION DIFERIDA','$idGrupoEmpresarial'),
					('$id_empresa', 1597, 'AMORTIZACION ACUMULADA','$idGrupoEmpresarial'),
					('$id_empresa', 1598, 'AGOTAMIENTO ACUMULADO','$idGrupoEmpresarial'),
					('$id_empresa', 1599, 'PROVISION ACTIVOS FIJOS','$idGrupoEmpresarial'),
					('$id_empresa', 159904, 'TERRENOS','$idGrupoEmpresarial'),
					('$id_empresa', 159916, 'EDIFICACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 159920, 'MAQUINARIA Y EQUIPO','$idGrupoEmpresarial'),
					('$id_empresa', 159924, 'EQUIPO DE OFICINA','$idGrupoEmpresarial'),
					('$id_empresa', 159928, 'EQUIPO DE COMUNICAICON Y COMPUTACION','$idGrupoEmpresarial'),
					('$id_empresa', 159932, 'LABORATORIO','$idGrupoEmpresarial'),
					('$id_empresa', 159940, 'FLOTA Y QUIPO D ETRANSPORTE','$idGrupoEmpresarial'),
					('$id_empresa', 16, 'ACTIVOS POR IMPUESTOS','$idGrupoEmpresarial'),
					('$id_empresa', 1605, 'ACTIVOS POR IMPUESTOS CORRIENTE','$idGrupoEmpresarial'),
					('$id_empresa', 160505, 'ANTICIPO DE IMPUESTO RENTA Y COMPLEMT.','$idGrupoEmpresarial'),
					('$id_empresa', 160510, 'RETENCION EN LA FUENTE','$idGrupoEmpresarial'),
					('$id_empresa', 160513, 'IVA RETENIDO EN VENTAS – RETEIVA','$idGrupoEmpresarial'),
					('$id_empresa', 160515, 'IMPUESTO DE INDUSTRIA Y COMERCIO','$idGrupoEmpresarial'),
					('$id_empresa', 160520, 'RETENCION CREE – RETECREE','$idGrupoEmpresarial'),
					('$id_empresa', 1610, 'ACTIVOS POR IMPUESTOS DIFERIDOS','$idGrupoEmpresarial'),
					('$id_empresa', 17, 'ACTIVOS INTANGIBLES','$idGrupoEmpresarial'),
					('$id_empresa', 1710, 'MARCAS','$idGrupoEmpresarial'),
					('$id_empresa', 171010, 'FORMADAS','$idGrupoEmpresarial'),
					('$id_empresa', 171099, 'AJUSTES POR INFLACION','$idGrupoEmpresarial'),
					('$id_empresa', 1715, 'PATENTES','$idGrupoEmpresarial'),
					('$id_empresa', 1720, 'CONCESIONES Y FRANQUICIAS','$idGrupoEmpresarial'),
					('$id_empresa', 1725, 'DERECHOS','$idGrupoEmpresarial'),
					('$id_empresa', 172535, 'EN BIENES RECIBIDOS EN ARRENDAMIENTO FIN','$idGrupoEmpresarial'),
					('$id_empresa', 172599, 'AJUSTES POR INFLACION','$idGrupoEmpresarial'),
					('$id_empresa', 1730, 'KNOW HOW','$idGrupoEmpresarial'),
					('$id_empresa', 1735, 'LICENCIAS','$idGrupoEmpresarial'),
					('$id_empresa', 173501, 'LICENCIAS','$idGrupoEmpresarial'),
					('$id_empresa', 1798, 'DEPRECIACION Y/O AMORTIZACION ACUMULADA','$idGrupoEmpresarial'),
					('$id_empresa', 179830, 'DERECHOS','$idGrupoEmpresarial'),
					('$id_empresa', 179840, 'DEPRECIACION Y O AMORTIZACION LICENCIAS','$idGrupoEmpresarial'),
					('$id_empresa', 179899, 'AJUSTES POR INFLACION','$idGrupoEmpresarial'),
					('$id_empresa', 1799, 'PROVISIONES','$idGrupoEmpresarial'),
					('$id_empresa', 18, 'OTROS ACTIVOS CORRIENTES','$idGrupoEmpresarial'),
					('$id_empresa', 1805, 'BIENES DE ARTE Y CULTURA','$idGrupoEmpresarial'),
					('$id_empresa', 1895, 'DIVERSOS','$idGrupoEmpresarial'),
					('$id_empresa', 1899, 'PROVISIONES','$idGrupoEmpresarial'),
					('$id_empresa', 19, 'INVERSIONES EN ASOCIADAS','$idGrupoEmpresarial'),
					('$id_empresa', 1905, 'DE INVERSIONES','$idGrupoEmpresarial'),
					('$id_empresa', 190505, 'ACCIONES','$idGrupoEmpresarial'),
					('$id_empresa', 190510, 'CUOTAS O PARTES DE INTERES SOCIAL','$idGrupoEmpresarial'),
					('$id_empresa', 1910, 'DE PROPIEDADES PLANTA Y EQUIPO','$idGrupoEmpresarial'),
					('$id_empresa', 191004, 'TERRENOS','$idGrupoEmpresarial'),
					('$id_empresa', 191008, 'CONSTRUCCIONES Y EDIFICACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 191012, 'MAQUINARIA Y EQUIPO','$idGrupoEmpresarial'),
					('$id_empresa', 191016, 'EQUIPO DE OFICINA','$idGrupoEmpresarial'),
					('$id_empresa', 191020, 'EQUIPO COMPUTACION Y COMUNICACION','$idGrupoEmpresarial'),
					('$id_empresa', 191024, 'EQUIPO MEDICO-CIENTIFICO','$idGrupoEmpresarial'),
					('$id_empresa', 191032, 'FLOTA Y EQUIPO DE TRANSPORTE','$idGrupoEmpresarial'),
					('$id_empresa', 191040, 'FLOTA Y EQUIPO DE TRANSPORTE','$idGrupoEmpresarial'),
					('$id_empresa', 191085, 'INTANGIBLES','$idGrupoEmpresarial'),
					('$id_empresa', 1995, 'VALORIZACION OTROS ACTIVOS','$idGrupoEmpresarial'),
					('$id_empresa', 199520, 'LICENCIAS AUTOCAD','$idGrupoEmpresarial'),
					('$id_empresa', 199525, 'LICENCIA PHOTOPIA','$idGrupoEmpresarial'),
					('$id_empresa', 199526, 'VALORIZACIONES SIESAMOBILE','$idGrupoEmpresarial'),
					('$id_empresa', 199527, 'LICENCIA SIESAMOBILE','$idGrupoEmpresarial'),
					('$id_empresa', 2, 'PASIVO','$idGrupoEmpresarial'),
					('$id_empresa', 21, 'PASIVOS FINANCIEROS','$idGrupoEmpresarial'),
					('$id_empresa', 2105, 'PRESTAMOS A CORTO PLAZO','$idGrupoEmpresarial'),
					('$id_empresa', 2110, 'PARTE CORRIENTE DE PRESTAMOS BANCARIOS','$idGrupoEmpresarial'),
					('$id_empresa', 2115, 'PARTE CORRIENTE DE OBLIGACIONES POR ARRENDAMIENTOS FINANCIEROS','$idGrupoEmpresarial'),
					('$id_empresa', 2120, 'SOBREGIROS BANCARIOS','$idGrupoEmpresarial'),
					('$id_empresa', 2125, 'PRESTAMOS BANCARIOS','$idGrupoEmpresarial'),
					('$id_empresa', 2130, 'OBLIGACIONES POR ARRENDAMIENTOS FINANCIEROS','$idGrupoEmpresarial'),
					('$id_empresa', 22, 'ACREEDORES COMERCIALES Y OTRAS CUENTAS POR PAGAR','$idGrupoEmpresarial'),
					('$id_empresa', 2205, 'NACIONALES','$idGrupoEmpresarial'),
					('$id_empresa', 220501, 'DE MATERIAS PRIMAS','$idGrupoEmpresarial'),
					('$id_empresa', 220502, 'DE SUMINISTROS','$idGrupoEmpresarial'),
					('$id_empresa', 220503, 'DE SERVICIOS','$idGrupoEmpresarial'),
					('$id_empresa', 2210, 'DEL EXTERIOR','$idGrupoEmpresarial'),
					('$id_empresa', 221005, 'ESTADOS UNIDOS DE AMERICA','$idGrupoEmpresarial'),
					('$id_empresa', 221010, 'JAPON','$idGrupoEmpresarial'),
					('$id_empresa', 221015, 'EUROPA','$idGrupoEmpresarial'),
					('$id_empresa', 221020, 'PERU','$idGrupoEmpresarial'),
					('$id_empresa', 2215, 'CUENTAS CORRIENTES COMERCIALES','$idGrupoEmpresarial'),
					('$id_empresa', 2220, 'CASA MATRIZ','$idGrupoEmpresarial'),
					('$id_empresa', 2225, 'COMPAÑIAS VINCULADAS','$idGrupoEmpresarial'),
					('$id_empresa', 2230, 'CUENTAS CORRIENTES COMERCIALES','$idGrupoEmpresarial'),
					('$id_empresa', 223005, 'CUENTAS CORRIENTES COMERCIALES','$idGrupoEmpresarial'),
					('$id_empresa', 2235, 'COSTOS Y GASTOS POR PAGAR','$idGrupoEmpresarial'),
					('$id_empresa', 223505, 'GASTOS FINANCIEROS','$idGrupoEmpresarial'),
					('$id_empresa', 223510, 'GASTOS LEGALES E IMPUESTOS','$idGrupoEmpresarial'),
					('$id_empresa', 223515, 'LIBROS SUSCRIPCIONES PERIODICOS REVISTAS','$idGrupoEmpresarial'),
					('$id_empresa', 223520, 'COMISIONES','$idGrupoEmpresarial'),
					('$id_empresa', 223525, 'HONORARIOS','$idGrupoEmpresarial'),
					('$id_empresa', 223530, 'SERVICIOS TECNICOS','$idGrupoEmpresarial'),
					('$id_empresa', 223535, 'SERVICIOS DE MANTENIMIENTO','$idGrupoEmpresarial'),
					('$id_empresa', 223540, 'ARRENDAMIENTOS','$idGrupoEmpresarial'),
					('$id_empresa', 223545, 'TRANSPORTES FLETES Y ACARREOS','$idGrupoEmpresarial'),
					('$id_empresa', 223550, 'SERVICIOS PUBLICOS','$idGrupoEmpresarial'),
					('$id_empresa', 223555, 'SEGUROS','$idGrupoEmpresarial'),
					('$id_empresa', 223560, 'GASTOS DE VIAJE','$idGrupoEmpresarial'),
					('$id_empresa', 223565, 'GASTOS DE REPRESENTACION Y RELACIONES PU','$idGrupoEmpresarial'),
					('$id_empresa', 223570, 'SERVICIOS ADUANEROS','$idGrupoEmpresarial'),
					('$id_empresa', 223595, 'OTROS COSTOS Y GASTOS POR PAGAR','$idGrupoEmpresarial'),
					('$id_empresa', 23, 'PASIVOS POR IMPUESTOS CORRIENTES','$idGrupoEmpresarial'),
					('$id_empresa', 2315, 'RETENCION EN LA FUENTE','$idGrupoEmpresarial'),
					('$id_empresa', 231505, 'SALARIOS Y PAGOS LABORALES','$idGrupoEmpresarial'),
					('$id_empresa', 231515, 'HONORARIOS','$idGrupoEmpresarial'),
					('$id_empresa', 231520, 'COMISIONES','$idGrupoEmpresarial'),
					('$id_empresa', 231525, 'SERVICIOS','$idGrupoEmpresarial'),
					('$id_empresa', 231530, 'ARRENDAMIENTOS','$idGrupoEmpresarial'),
					('$id_empresa', 231540, 'COMPRAS','$idGrupoEmpresarial'),
					('$id_empresa', 231570, 'OTRAS RETENCIONES Y PATRIMONIO','$idGrupoEmpresarial'),
					('$id_empresa', 231575, 'AUTORETENCIONES','$idGrupoEmpresarial'),
					('$id_empresa', 231590, 'PAGO DE RETENCION','$idGrupoEmpresarial'),
					('$id_empresa', 2317, 'IMPUESTO A LAS VENTAS RETENIDO','$idGrupoEmpresarial'),
					('$id_empresa', 231701, 'IVA RETENIDO 50 %','$idGrupoEmpresarial'),
					('$id_empresa', 231702, 'IVA RETENIDO 15 %','$idGrupoEmpresarial'),
					('$id_empresa', 2318, 'IMPUESTO DE INDUSTRIA Y COMERCIO RETENID','$idGrupoEmpresarial'),
					('$id_empresa', 231801, 'IMPTO IND Y CIO RETENIDO','$idGrupoEmpresarial'),
					('$id_empresa', 23180133, 'TARIFA 2.2','$idGrupoEmpresarial'),
					('$id_empresa', 231802, 'PAGO DE RETENCIONES','$idGrupoEmpresarial'),
					('$id_empresa', 2320, 'RETENCIONES Y APORTES DE NOMINA','$idGrupoEmpresarial'),
					('$id_empresa', 232005, 'APORTES A ENTIDADES PROMOTORAS DE SALUD','$idGrupoEmpresarial'),
					('$id_empresa', 232006, 'APORTES A ADMINISTRADORAS DE RIESGOS PRO','$idGrupoEmpresarial'),
					('$id_empresa', 232010, 'APORTES AL ICBF. SENA Y CAJA DE COMPENSA','$idGrupoEmpresarial'),
					('$id_empresa', 232025, 'EMBARGOS JUDICIALES','$idGrupoEmpresarial'),
					('$id_empresa', 232095, 'OTROS RETENCION DE NOMINA','$idGrupoEmpresarial'),
					('$id_empresa', 2325, 'CUOTAS POR DEVOLVER','$idGrupoEmpresarial'),
					('$id_empresa', 2330, 'ACREEDORES VARIOS','$idGrupoEmpresarial'),
					('$id_empresa', 233030, 'FONDOS DE CESANTIAS Y/O PENSIONES','$idGrupoEmpresarial'),
					('$id_empresa', 2345, 'DE SERVICIOS','$idGrupoEmpresarial'),
					('$id_empresa', 234595, 'DE SERVICIOS','$idGrupoEmpresarial'),
					('$id_empresa', 2358, 'IMPUESTOS SOBRE LAS VENTAS POR PAGAR','$idGrupoEmpresarial'),
					('$id_empresa', 235801, 'GENERADO POR VENTAS','$idGrupoEmpresarial'),
					('$id_empresa', 235802, 'IMPUESTO DESCONTABLE (DB)','$idGrupoEmpresarial'),
					('$id_empresa', 235803, 'IVA POR PAGAR','$idGrupoEmpresarial'),
					('$id_empresa', 24, 'PASIVOS POR IMPUESTOS DIFERIDOS ','$idGrupoEmpresarial'),
					('$id_empresa', 25, 'PARTE CORRIENTE DE OBLIGACIONES POR BENEFICIOS A LOS EMPLEADOS','$idGrupoEmpresarial'),
					('$id_empresa', 2505, 'SALARIOS POR PAGAR','$idGrupoEmpresarial'),
					('$id_empresa', 250505, 'SALARIOS POR PAGAR','$idGrupoEmpresarial'),
					('$id_empresa', 2510, 'CESANTIAS CONSOLIDADAS','$idGrupoEmpresarial'),
					('$id_empresa', 251005, 'LEY LABORAL ANTERIOR','$idGrupoEmpresarial'),
					('$id_empresa', 251010, 'LEY 50 DE 1990 Y NORMAS POSTERIORES','$idGrupoEmpresarial'),
					('$id_empresa', 2515, 'INTERESES SOBRE CESANTIAS','$idGrupoEmpresarial'),
					('$id_empresa', 251505, 'INTERESES SOBRE CESANTIAS','$idGrupoEmpresarial'),
					('$id_empresa', 2520, 'PRIMA DE SERVICIOS','$idGrupoEmpresarial'),
					('$id_empresa', 252005, 'PRIMA DE SERVICIOS','$idGrupoEmpresarial'),
					('$id_empresa', 2525, 'VACACIONES CONSOLIDADAS','$idGrupoEmpresarial'),
					('$id_empresa', 252505, 'VACACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 2530, 'PRESTACIONES EXTRALEGALES','$idGrupoEmpresarial'),
					('$id_empresa', 253005, 'PRIMAS','$idGrupoEmpresarial'),
					('$id_empresa', 26, 'PROVISIONES A CORTO PLAZO','$idGrupoEmpresarial'),
					('$id_empresa', 2605, 'PARA COSTOS Y GASTOS','$idGrupoEmpresarial'),
					('$id_empresa', 260525, 'TRANSPORTES,FLETES Y ACARREOS','$idGrupoEmpresarial'),
					('$id_empresa', 260595, 'OTROS','$idGrupoEmpresarial'),
					('$id_empresa', 2610, 'PARA OBLIGACIONES LABORALES','$idGrupoEmpresarial'),
					('$id_empresa', 261095, 'OTRAS','$idGrupoEmpresarial'),
					('$id_empresa', 261096, 'APORTES SEGURIDAD SOCIAL EMPLEADO','$idGrupoEmpresarial'),
					('$id_empresa', 2615, 'PARA OBLIGACIONES FISCALES','$idGrupoEmpresarial'),
					('$id_empresa', 261505, 'DE RENTA Y COMPLEMENTARIOS','$idGrupoEmpresarial'),
					('$id_empresa', 261510, 'DE INDUSTRIA Y COMERCIO','$idGrupoEmpresarial'),
					('$id_empresa', 2620, 'PENSIONES DE JUBILACION','$idGrupoEmpresarial'),
					('$id_empresa', 2625, 'PARA OBRAS DE URBANISMO','$idGrupoEmpresarial'),
					('$id_empresa', 2630, 'PARA MANTENIMIENTOS Y REPARACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 2635, 'PARA CONTINGENCIAS','$idGrupoEmpresarial'),
					('$id_empresa', 2640, 'PARA OBLIGACIONES DE GARANTIAS','$idGrupoEmpresarial'),
					('$id_empresa', 2695, 'PROVISIONES DIVERSAS','$idGrupoEmpresarial'),
					('$id_empresa', 269595, 'PASIVO POR LEGALIZAR','$idGrupoEmpresarial'),
					('$id_empresa', 269596, 'CAJAS MENORES POR LEGALIZAR','$idGrupoEmpresarial'),
					('$id_empresa', 3, 'PATRIMONIO','$idGrupoEmpresarial'),
					('$id_empresa', 31, 'CAPITAL EN ACCIONES','$idGrupoEmpresarial'),
					('$id_empresa', 3105, 'CAPITAL SUSCRITO Y PAGADO','$idGrupoEmpresarial'),
					('$id_empresa', 310505, 'CAPITAL AUTORIZADO','$idGrupoEmpresarial'),
					('$id_empresa', 310510, 'CAPITAL POR SUSCRIBIR (DB)','$idGrupoEmpresarial'),
					('$id_empresa', 32, 'GANANCIAS ACUMULADAS','$idGrupoEmpresarial'),
					('$id_empresa', 3205, 'GANANCIAS SOBRE COBERTURAS DE RIESGOS DE TASA DE CAMBIO DE LA MONEDA EXTRANJERA DE COMPROMISOS EN FIRME','$idGrupoEmpresarial'),
					('$id_empresa', 3210, 'PARTICIPACIONES NO CONTROLADORAS','$idGrupoEmpresarial'),
					('$id_empresa', 3215, 'PATRIMONIO ATRIBUIBLE A LOS PROPIETARIOS DE LA CONTROLADORA ','$idGrupoEmpresarial'),
					('$id_empresa', 4, 'INGRESOS','$idGrupoEmpresarial'),
					('$id_empresa', 41, 'INGRESOS DE ACTIVIDADES ORDINARIAS','$idGrupoEmpresarial'),
					('$id_empresa', 4105, 'AGRICULTURA, GANADERIA, CAZA Y SELVICULTURA','$idGrupoEmpresarial'),
					('$id_empresa', 4110, 'PESCA','$idGrupoEmpresarial'),
					('$id_empresa', 4115, 'EXPLOTACION DE MINAS Y CANTERAS','$idGrupoEmpresarial'),
					('$id_empresa', 4120, 'INDUSTRIAS MANUFACTURERAS','$idGrupoEmpresarial'),
					('$id_empresa', 412061, 'FORJA, PRENSADO, LAMINADO DE METAL','$idGrupoEmpresarial'),
					('$id_empresa', 412070, 'ELABORACION DE EQUIPO DE ILUMINACION','$idGrupoEmpresarial'),
					('$id_empresa', 4125, 'SUMINISTROS DE ELECTRICIDAD, GAS Y AGUA','$idGrupoEmpresarial'),
					('$id_empresa', 4130, 'CONSTRUCCION','$idGrupoEmpresarial'),
					('$id_empresa', 4135, 'COMERCIO AL POR MAYOR Y AL POR MENOR','$idGrupoEmpresarial'),
					('$id_empresa', 413502, 'VENTA DE VEHICULOS AUTOMOTORES','$idGrupoEmpresarial'),
					('$id_empresa', 413504, 'MANTENIMIENTO, REPARACION Y LAVADO DE VEHICULOS AUTOMOTORES','$idGrupoEmpresarial'),
					('$id_empresa', 413506, 'VENTA DE PARTES, PIEZAS Y ACCESORIOS DE VEHICULOS AUTOMOTORES','$idGrupoEmpresarial'),
					('$id_empresa', 413508, 'VENTA DE COMBUSTIBLES SOLIDOS, LIQUIDOS, GASEOSOS','$idGrupoEmpresarial'),
					('$id_empresa', 413510, 'VENTA DE LUBRICANTES, ADITIVOS, LLANTAS Y LUJOS PARA AUTOMOTORES','$idGrupoEmpresarial'),
					('$id_empresa', 413512, 'VENTA A CAMBIO DE RETRIBUCION O POR CONTRATA','$idGrupoEmpresarial'),
					('$id_empresa', 413514, 'VENTA DE INSUMOS, MATERIAS PRIMAS AGROPECUARIAS Y FLORES','$idGrupoEmpresarial'),
					('$id_empresa', 413516, 'VENTA DE OTROS INSUMOS Y MATERIAS PRIMAS NO AGROPECUARIAS','$idGrupoEmpresarial'),
					('$id_empresa', 413518, 'VENTA DE ANIMALES VIVOS Y CUEROS','$idGrupoEmpresarial'),
					('$id_empresa', 413520, 'VENTA DE PRODUCTOS EN ALMACENES NO ESPECIALIZADOS','$idGrupoEmpresarial'),
					('$id_empresa', 413522, 'VENTA DE PRODUCTOS AGROPECUARIOS','$idGrupoEmpresarial'),
					('$id_empresa', 413524, 'VENTA DE PRODUCTOS TEXTILES, DE VESTIR, DE CUERO Y CALZADO','$idGrupoEmpresarial'),
					('$id_empresa', 413526, 'VENTA DE PAPEL Y CARTON','$idGrupoEmpresarial'),
					('$id_empresa', 413528, 'VENTA DE LIBROS, REVISTAS, ELEMENTOS DE PAPELERIA, UTILES Y TEXTOS ESCOLARES','$idGrupoEmpresarial'),
					('$id_empresa', 413530, 'VENTA DE JUEGOS, JUGUETES Y ARTICULOS DEPORTIVOS','$idGrupoEmpresarial'),
					('$id_empresa', 413532, 'VENTA DE INSTRUMENTOS QUIRURGICOS Y ORTOPEDICOS','$idGrupoEmpresarial'),
					('$id_empresa', 413534, 'VENTA DE ARTICULOS EN RELOJERIAS Y JOYERIAS','$idGrupoEmpresarial'),
					('$id_empresa', 413536, 'VENTA DE ELECTRODOMESTICOS Y MUEBLES','$idGrupoEmpresarial'),
					('$id_empresa', 413538, 'VENTA DE PRODUCTOS DE ASEO, FARMACEUTICOS, MEDICINALES, Y ARTICULOS DE TOCADOR','$idGrupoEmpresarial'),
					('$id_empresa', 413540, 'VENTA DE CUBIERTOS, VAJILLAS, CRISTALERIA, PORCELANAS, CERAMICAS Y OTROS ARTICULOS DE USO DOMESTICO','$idGrupoEmpresarial'),
					('$id_empresa', 413542, 'VENTA DE MATERIALES DE CONSTRUCCION, FONTANERIA Y CALEFACCION','$idGrupoEmpresarial'),
					('$id_empresa', 413544, 'VENTA DE PINTURAS Y LACAS','$idGrupoEmpresarial'),
					('$id_empresa', 413546, 'VENTA DE PRODUCTOS DE VIDRIOS Y MARQUETERIA','$idGrupoEmpresarial'),
					('$id_empresa', 413548, 'VENTA DE HERRAMIENTAS Y ARTICULOS DE FERRETERIA','$idGrupoEmpresarial'),
					('$id_empresa', 413550, 'VENTA DE QUIMICOS','$idGrupoEmpresarial'),
					('$id_empresa', 413552, 'VENTA DE PRODUCTOS INTERMEDIOS, DESPERDICIOS Y DESECHOS','$idGrupoEmpresarial'),
					('$id_empresa', 413554, 'VENTA DE MAQUINARIA, EQUIPO DE OFICINA Y PROGRAMAS DE COMPUTADOR','$idGrupoEmpresarial'),
					('$id_empresa', 413556, 'VENTA DE ARTICULOS EN CACHARRERIAS Y MISCELANEAS','$idGrupoEmpresarial'),
					('$id_empresa', 413558, 'VENTA DE INSTRUMENTOS MUSICALES','$idGrupoEmpresarial'),
					('$id_empresa', 413560, 'VENTA DE ARTICULOS EN CASAS DE EMPEÃ?O Y PRENDERIAS','$idGrupoEmpresarial'),
					('$id_empresa', 413562, 'VENTA DE EQUIPO FOTOGRAFICO','$idGrupoEmpresarial'),
					('$id_empresa', 413564, 'VENTA DE EQUIPO OPTICO Y DE PRECISION','$idGrupoEmpresarial'),
					('$id_empresa', 413566, 'VENTA DE EMPAQUES','$idGrupoEmpresarial'),
					('$id_empresa', 413568, 'VENTA DE EQUIPO PROFESIONAL Y CIENTIFICO','$idGrupoEmpresarial'),
					('$id_empresa', 413570, 'VENTA DE LOTERIAS, RIFAS, CHANCE, APUESTAS Y SIMILARES','$idGrupoEmpresarial'),
					('$id_empresa', 413572, 'REPARACION DE EFECTOS PERSONALES Y ELECTRODOMESTICOS','$idGrupoEmpresarial'),
					('$id_empresa', 413595, 'VENTA DE OTROS PRODUCTOS','$idGrupoEmpresarial'),
					('$id_empresa', 413599, 'AJUSTES POR INFLACION','$idGrupoEmpresarial'),
					('$id_empresa', 4140, 'HOTELES Y RESTAURANTES','$idGrupoEmpresarial'),
					('$id_empresa', 4145, 'TRANSPORTE, ALMACENAMIENTO Y COMUNICACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 4150, 'ACTIVIDAD FINANCIERA','$idGrupoEmpresarial'),
					('$id_empresa', 415010, 'DIVIDENDOS DE SOCIEDADES ANONIMAS','$idGrupoEmpresarial'),
					('$id_empresa', 4155, 'ACTIVIDADES INMOBILIARIAS, EMPRESARIALES Y DE ALQUILER','$idGrupoEmpresarial'),
					('$id_empresa', 4160, 'ENSEÑANZAS','$idGrupoEmpresarial'),
					('$id_empresa', 4165, 'SERVICIOS SOCIALES Y DE SALUD','$idGrupoEmpresarial'),
					('$id_empresa', 4170, 'OTRAS ACTIVIDADES DE SERVICIOS COMUNITARIOS, SOCIALES Y PERSONALES','$idGrupoEmpresarial'),
					('$id_empresa', 4175, 'DEVOLUCIONES EN VENTAS','$idGrupoEmpresarial'),
					('$id_empresa', 417501, 'DEVOLUCIONES EN VENTAS PRODUCT. TERMINAD','$idGrupoEmpresarial'),
					('$id_empresa', 417502, 'DEVOLUCIONES EN VENTAS MATERIA PRIMA','$idGrupoEmpresarial'),
					('$id_empresa', 42, 'OTROS INGRESOS','$idGrupoEmpresarial'),
					('$id_empresa', 4205, 'OTRAS VENTAS','$idGrupoEmpresarial'),
					('$id_empresa', 420505, 'MATERIA PRIMA','$idGrupoEmpresarial'),
					('$id_empresa', 420530, 'ENVASES Y EMPAQUES','$idGrupoEmpresarial'),
					('$id_empresa', 4210, 'FINANCIEROS','$idGrupoEmpresarial'),
					('$id_empresa', 421005, 'INTERESES','$idGrupoEmpresarial'),
					('$id_empresa', 421020, 'DIFERENCIA EN CAMBIO','$idGrupoEmpresarial'),
					('$id_empresa', 421021, 'DIERENCIA EN CAMBIO NO REALIZADA','$idGrupoEmpresarial'),
					('$id_empresa', 421040, 'DESCUENTOS COMERCIALES CONDICIONADOS','$idGrupoEmpresarial'),
					('$id_empresa', 421045, 'DESCUENTOS BANCARIOS','$idGrupoEmpresarial'),
					('$id_empresa', 421065, 'AJUSTE AL PESO','$idGrupoEmpresarial'),
					('$id_empresa', 421095, 'OTROS','$idGrupoEmpresarial'),
					('$id_empresa', 4215, 'DIVIDENDOS Y PARTICIPACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 4218, 'INGRESOS METODOS DE PARTICIPACION','$idGrupoEmpresarial'),
					('$id_empresa', 4220, 'ARRENDAMIENTOS','$idGrupoEmpresarial'),
					('$id_empresa', 422010, 'CONSTRUCCIONES Y EDIFICIOS','$idGrupoEmpresarial'),
					('$id_empresa', 4225, 'COMISIONES','$idGrupoEmpresarial'),
					('$id_empresa', 4230, 'HONORARIOS','$idGrupoEmpresarial'),
					('$id_empresa', 4235, 'SERVICIOS','$idGrupoEmpresarial'),
					('$id_empresa', 423580, 'SERVICIOS','$idGrupoEmpresarial'),
					('$id_empresa', 423595, 'OTROS','$idGrupoEmpresarial'),
					('$id_empresa', 4240, 'UTILIDAD EN VENTAS DE INVERSIONES','$idGrupoEmpresarial'),
					('$id_empresa', 4245, 'UTILIDAD EN VENTA PROP.PLANTA Y EQUIPO','$idGrupoEmpresarial'),
					('$id_empresa', 424516, 'CONSTRUCCIONES Y EDIFICACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 424540, 'FLOTA, EQUIPO DE TRANSPORTE','$idGrupoEmpresarial'),
					('$id_empresa', 4250, 'RECUPERACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 425005, 'DEUDAS MALAS','$idGrupoEmpresarial'),
					('$id_empresa', 425025, 'REINTEGRO DE GARANTIAS','$idGrupoEmpresarial'),
					('$id_empresa', 425035, 'DE PROVISIONES','$idGrupoEmpresarial'),
					('$id_empresa', 425045, 'DE DEPRECIACION','$idGrupoEmpresarial'),
					('$id_empresa', 425050, 'REINTEGRO DE OTROS COSTOS Y GASTOS','$idGrupoEmpresarial'),
					('$id_empresa', 4255, 'INDEMNIZACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 425505, 'POR SINIESTRO','$idGrupoEmpresarial'),
					('$id_empresa', 425525, 'POR PERDIDA DE MERCANCIA','$idGrupoEmpresarial'),
					('$id_empresa', 425540, 'POR INCAPACIDADES','$idGrupoEmpresarial'),
					('$id_empresa', 4260, 'PARTICIPACIONES EN CONCESIONES','$idGrupoEmpresarial'),
					('$id_empresa', 4265, 'INGRESOS DE EJERCICIOS ANTERIORES','$idGrupoEmpresarial'),
					('$id_empresa', 426501, 'INTERESES','$idGrupoEmpresarial'),
					('$id_empresa', 426510, 'EJERCICIOS ANTERIORES','$idGrupoEmpresarial'),
					('$id_empresa', 426540, 'POR INCAPACIDADES','$idGrupoEmpresarial'),
					('$id_empresa', 426550, 'SALDOS CARTERA NO COBRADOS','$idGrupoEmpresarial'),
					('$id_empresa', 4275, 'DEVOLUCIONES EN OTRAS VENTAS (DB)','$idGrupoEmpresarial'),
					('$id_empresa', 4295, 'DIVERSOS','$idGrupoEmpresarial'),
					('$id_empresa', 429505, 'APROVECHAMIENTOS','$idGrupoEmpresarial'),
					('$id_empresa', 429535, 'PREAVISOS DESCONTADOS','$idGrupoEmpresarial'),
					('$id_empresa', 429540, 'RECOBRO DE DANOS','$idGrupoEmpresarial'),
					('$id_empresa', 429549, 'RECONOCIMIENTOS I.S.S','$idGrupoEmpresarial'),
					('$id_empresa', 429581, 'AJUSTE AL PESO','$idGrupoEmpresarial'),
					('$id_empresa', 429595, 'OTROS','$idGrupoEmpresarial'),
					('$id_empresa', 5, 'GASTOS','$idGrupoEmpresarial'),
					('$id_empresa', 51, 'GASTOS DE ADMINISTRACION ','$idGrupoEmpresarial'),
					('$id_empresa', 5105, 'GASTOS DE ADMINISTRACION ','$idGrupoEmpresarial'),
					('$id_empresa', 5110, 'GASTOS POR BENEFICIOS A LOS EMPLEADOS','$idGrupoEmpresarial'),
					('$id_empresa', 511006, 'SUELDOS','$idGrupoEmpresarial'),
					('$id_empresa', 511015, 'HORAS EXTRAS','$idGrupoEmpresarial'),
					('$id_empresa', 511018, 'COMISIONES','$idGrupoEmpresarial'),
					('$id_empresa', 511024, 'INCAPACIDADES','$idGrupoEmpresarial'),
					('$id_empresa', 511027, 'AUXILIO DE TRANSPORTE','$idGrupoEmpresarial'),
					('$id_empresa', 511030, 'CESANTIAS','$idGrupoEmpresarial'),
					('$id_empresa', 511033, 'INTERESES SOBRE CESANTIAS','$idGrupoEmpresarial'),
					('$id_empresa', 511036, 'PRIMA DE SERVICIOS','$idGrupoEmpresarial'),
					('$id_empresa', 511039, 'VACACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 511042, 'PRIMAS EXTRALEGALES','$idGrupoEmpresarial'),
					('$id_empresa', 511045, 'AUXILIOS','$idGrupoEmpresarial'),
					('$id_empresa', 511048, 'BONIFICACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 511051, 'DOTACION Y SUMINISTRO A TRABAJADORES','$idGrupoEmpresarial'),
					('$id_empresa', 511060, 'INDEMNIZACIONES LABORALES','$idGrupoEmpresarial'),
					('$id_empresa', 511063, 'CAPACITACION AL PERSONAL','$idGrupoEmpresarial'),
					('$id_empresa', 511066, 'GASTOS DEPORTIVOS/RECREACION (BIENESTAR)','$idGrupoEmpresarial'),
					('$id_empresa', 511068, 'APORTES A ADMTRAS. DE RIESGOS PROFESIONA','$idGrupoEmpresarial'),
					('$id_empresa', 511069, 'APORTES A ENTIDADES PROMOTORAS DE SALUD','$idGrupoEmpresarial'),
					('$id_empresa', 511070, 'APORTES A FONDOS DE PENSIONES Y/O CESANT','$idGrupoEmpresarial'),
					('$id_empresa', 511072, 'APORTES CAJAS DE COMPENSACION','$idGrupoEmpresarial'),
					('$id_empresa', 511075, 'APORTES I.C.B.F.','$idGrupoEmpresarial'),
					('$id_empresa', 511078, 'APORTES SENA','$idGrupoEmpresarial'),
					('$id_empresa', 511084, 'GASTOS MEDICOS Y DROGAS','$idGrupoEmpresarial'),
					('$id_empresa', 511095, 'GASTOS DE BIENESTAR AL PERSONAL','$idGrupoEmpresarial'),
					('$id_empresa', 5115, 'GASTOS DE DEPRECIACION Y AMORTIZACION ','$idGrupoEmpresarial'),
					('$id_empresa', 511505, 'CONSTRUCCIONES Y EDIFICACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 511510, 'DEPRECIACION MAQUINARIA Y EQUIPO','$idGrupoEmpresarial'),
					('$id_empresa', 511515, 'EQUIPO DE OFICINA','$idGrupoEmpresarial'),
					('$id_empresa', 511520, 'EQUIPO DE COMPUTACION Y COMUNICACION','$idGrupoEmpresarial'),
					('$id_empresa', 511535, 'FLOTA Y EQUIPO DE TRANSPORTE','$idGrupoEmpresarial'),
					('$id_empresa', 511595, 'DEPRECIACION OTROS EQUIPOS','$idGrupoEmpresarial'),
					('$id_empresa', 52, 'OTROS GASTOS','$idGrupoEmpresarial'),
					('$id_empresa', 5205, 'GASTOS DE PERSONAL','$idGrupoEmpresarial'),
					('$id_empresa', 520506, 'SUELDOS','$idGrupoEmpresarial'),
					('$id_empresa', 520515, 'HORAS EXTRAS','$idGrupoEmpresarial'),
					('$id_empresa', 520518, 'COMISIONES','$idGrupoEmpresarial'),
					('$id_empresa', 520524, 'INCAPACIDADES','$idGrupoEmpresarial'),
					('$id_empresa', 520527, 'AUXILIO DE TRANSPORTE','$idGrupoEmpresarial'),
					('$id_empresa', 520530, 'CESANTIAS','$idGrupoEmpresarial'),
					('$id_empresa', 520533, 'INTERESES SOBRE CESANTIAS','$idGrupoEmpresarial'),
					('$id_empresa', 520536, 'PRIMA DE SERVICIOS','$idGrupoEmpresarial'),
					('$id_empresa', 520539, 'VACACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 520542, 'PRIMAS EXTRALEGALES','$idGrupoEmpresarial'),
					('$id_empresa', 520545, 'AUXILIOS','$idGrupoEmpresarial'),
					('$id_empresa', 520548, 'BONIFICACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 520551, 'DOTACION Y SUMINISTROS A TRABAJADORES','$idGrupoEmpresarial'),
					('$id_empresa', 520560, 'INDEMNIZACIONES LABORALES','$idGrupoEmpresarial'),
					('$id_empresa', 520563, 'CAPACITACION AL PERSONAL','$idGrupoEmpresarial'),
					('$id_empresa', 520568, 'APORTES A ADTRAS DE RIESGOS PROFESIONALE','$idGrupoEmpresarial'),
					('$id_empresa', 520569, 'APORTES A ENTIDADES PROMOTORAS DE SALUD','$idGrupoEmpresarial'),
					('$id_empresa', 520570, 'APORTES A FONDOS DE PENSIONES Y/O CESANT','$idGrupoEmpresarial'),
					('$id_empresa', 520572, 'APORTES CAJA DE COMPENSACION FAMILIAR','$idGrupoEmpresarial'),
					('$id_empresa', 520575, 'APORTES I.C.B.F','$idGrupoEmpresarial'),
					('$id_empresa', 520578, 'SENA','$idGrupoEmpresarial'),
					('$id_empresa', 520584, 'GASTOS MEDICOS Y DROGAS','$idGrupoEmpresarial'),
					('$id_empresa', 520595, 'GASTOS DE BIENESTAR AL PERSONAL','$idGrupoEmpresarial'),
					('$id_empresa', 5210, 'HONORARIOS','$idGrupoEmpresarial'),
					('$id_empresa', 521025, 'ASESORIA JURIDICA','$idGrupoEmpresarial'),
					('$id_empresa', 521035, 'ASESORIA TECNICA','$idGrupoEmpresarial'),
					('$id_empresa', 521045, 'COMISIONES','$idGrupoEmpresarial'),
					('$id_empresa', 521095, 'OTROS','$idGrupoEmpresarial'),
					('$id_empresa', 5215, 'IMPUESTOS','$idGrupoEmpresarial'),
					('$id_empresa', 521505, 'INDUSTRIA Y COMERCIO','$idGrupoEmpresarial'),
					('$id_empresa', 521510, 'DE TIMBRES','$idGrupoEmpresarial'),
					('$id_empresa', 521540, 'DE VEHICULOS','$idGrupoEmpresarial'),
					('$id_empresa', 521570, 'IVA DESCONTABLE COSTOS Y GASTOS','$idGrupoEmpresarial'),
					('$id_empresa', 521575, 'IMPUESTO AL CONSUMO','$idGrupoEmpresarial'),
					('$id_empresa', 521595, 'OTROS','$idGrupoEmpresarial'),
					('$id_empresa', 5220, 'ARRENDAMIENTOS','$idGrupoEmpresarial'),
					('$id_empresa', 522010, 'CONSTRUCCIONES Y EDIFICACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 522015, 'ALQUILER MAQUINARIA Y EQUIPO','$idGrupoEmpresarial'),
					('$id_empresa', 522040, 'FLOTA Y EQUIPO DE TRANSPORTE','$idGrupoEmpresarial'),
					('$id_empresa', 522095, 'OTROS','$idGrupoEmpresarial'),
					('$id_empresa', 5225, 'CONTRIBUCIONES Y AFILIACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 522505, 'CONTRIBUCIONES','$idGrupoEmpresarial'),
					('$id_empresa', 522510, 'AFILIACIONES Y SOSTENIMIENTO','$idGrupoEmpresarial'),
					('$id_empresa', 522515, 'SUSCRIPCION AUTOCAD','$idGrupoEmpresarial'),
					('$id_empresa', 522520, 'CERTIFICACIONES RETILAP','$idGrupoEmpresarial'),
					('$id_empresa', 5230, 'SEGUROS','$idGrupoEmpresarial'),
					('$id_empresa', 523010, 'DE CUMPLIMIENTO','$idGrupoEmpresarial'),
					('$id_empresa', 523025, 'DE INCENDIO','$idGrupoEmpresarial'),
					('$id_empresa', 523030, 'TERREMOTO','$idGrupoEmpresarial'),
					('$id_empresa', 523035, 'SUSTRACCION Y HURTO','$idGrupoEmpresarial'),
					('$id_empresa', 523040, 'FLOTA Y EQUIPO DE TRANSPORTE','$idGrupoEmpresarial'),
					('$id_empresa', 523060, 'RESPONSABILIDAD CIVIL Y EXTRACONTRATUAL','$idGrupoEmpresarial'),
					('$id_empresa', 523075, 'OBLIGATORIO ACCIDENTE DE TRANSITO','$idGrupoEmpresarial'),
					('$id_empresa', 523095, 'OTROS','$idGrupoEmpresarial'),
					('$id_empresa', 5235, 'SERVICIOS','$idGrupoEmpresarial'),
					('$id_empresa', 523505, 'ASEO Y VIGILANCIA','$idGrupoEmpresarial'),
					('$id_empresa', 523510, 'TEMPORALES','$idGrupoEmpresarial'),
					('$id_empresa', 523515, 'PROCESAMIENTO ELECTRONICO DE DATOS','$idGrupoEmpresarial'),
					('$id_empresa', 523520, 'INTERNET','$idGrupoEmpresarial'),
					('$id_empresa', 523525, 'ACUEDUCTO Y ALCANTARILLADO','$idGrupoEmpresarial'),
					('$id_empresa', 523530, 'ENERGIA','$idGrupoEmpresarial'),
					('$id_empresa', 523535, 'TELEFONO','$idGrupoEmpresarial'),
					('$id_empresa', 523540, 'CORREO, PORTES Y TELEGRAMAS','$idGrupoEmpresarial'),
					('$id_empresa', 523545, 'FAX Y TELEX','$idGrupoEmpresarial'),
					('$id_empresa', 523550, 'TRANSPORTE, FLETES Y ACARREOS','$idGrupoEmpresarial'),
					('$id_empresa', 523555, 'GAS','$idGrupoEmpresarial'),
					('$id_empresa', 523560, 'PUBLICIDAD, PROPAGANDA Y PROMOCION','$idGrupoEmpresarial'),
					('$id_empresa', 523561, 'SERVICIOS DE MANO DE OBRA/INSTALACION','$idGrupoEmpresarial'),
					('$id_empresa', 523595, 'OTROS','$idGrupoEmpresarial'),
					('$id_empresa', 5240, 'GASTOS LEGALES','$idGrupoEmpresarial'),
					('$id_empresa', 524005, 'NOTARIALES','$idGrupoEmpresarial'),
					('$id_empresa', 524010, 'REGISTRO MERCANTIL','$idGrupoEmpresarial'),
					('$id_empresa', 524015, 'TRAMITES Y LICENCIAS','$idGrupoEmpresarial'),
					('$id_empresa', 524020, 'ADUANEROS','$idGrupoEmpresarial'),
					('$id_empresa', 524030, 'PAPELERIA UTILES ESCRITORIO','$idGrupoEmpresarial'),
					('$id_empresa', 524095, 'OTROS','$idGrupoEmpresarial'),
					('$id_empresa', 5245, 'MANTENIMIENTO Y REPARACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 524510, 'CONSTRUCCIONES Y EDIFICACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 524515, 'MAQUINARIA Y EQUIPO','$idGrupoEmpresarial'),
					('$id_empresa', 524520, 'EQUIPO DE OFICINA','$idGrupoEmpresarial'),
					('$id_empresa', 524525, 'EQUIPO DE COMPUTACION Y COMUNICACION','$idGrupoEmpresarial'),
					('$id_empresa', 524540, 'FLOTA Y EQUIPO DE TRANSPORTES','$idGrupoEmpresarial'),
					('$id_empresa', 524595, 'OTROS','$idGrupoEmpresarial'),
					('$id_empresa', 5250, 'ADECUACION E INSTALACION','$idGrupoEmpresarial'),
					('$id_empresa', 525005, 'INSTALACIONES ELECTRICAS','$idGrupoEmpresarial'),
					('$id_empresa', 525010, 'ARREGLOS ORNAMENTALES','$idGrupoEmpresarial'),
					('$id_empresa', 525015, 'REPARACIONES LOCATIVAS','$idGrupoEmpresarial'),
					('$id_empresa', 5255, 'GASTOS DE VIAJE','$idGrupoEmpresarial'),
					('$id_empresa', 525505, 'ALOJAMIENTO Y MANUTENCION','$idGrupoEmpresarial'),
					('$id_empresa', 525515, 'PASAJES AEREOS','$idGrupoEmpresarial'),
					('$id_empresa', 525520, 'PASAJES TERRESTRES','$idGrupoEmpresarial'),
					('$id_empresa', 525530, 'PEAJES','$idGrupoEmpresarial'),
					('$id_empresa', 525535, 'PARQUEADEROS','$idGrupoEmpresarial'),
					('$id_empresa', 525540, 'REEMBOLSO GASTOS VIAJE','$idGrupoEmpresarial'),
					('$id_empresa', 525595, 'OTROS','$idGrupoEmpresarial'),
					('$id_empresa', 5260, 'DEPRECIACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 526010, 'DEPRECIAICON MAQUINARIA Y EQUIPO','$idGrupoEmpresarial'),
					('$id_empresa', 526015, 'DEPRECIACION EQUIPO DE OFICINA','$idGrupoEmpresarial'),
					('$id_empresa', 526020, 'DEPRECIACION EQUIPO DE COMPUTO','$idGrupoEmpresarial'),
					('$id_empresa', 526035, 'FLOTA Y EQUIPO DE TRANSPORTE','$idGrupoEmpresarial'),
					('$id_empresa', 526095, 'DEPRECIACION OTROS EQUIPOS','$idGrupoEmpresarial'),
					('$id_empresa', 5265, 'AMORTIZACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 526510, 'INTANGIBLES','$idGrupoEmpresarial'),
					('$id_empresa', 5270, 'VARIACIONES EN PRODUCCION','$idGrupoEmpresarial'),
					('$id_empresa', 527001, 'VARIACIONES EN MATERIA PRIMA','$idGrupoEmpresarial'),
					('$id_empresa', 527002, 'VARIACIONES EN MANO DE OBRA DIRECTA','$idGrupoEmpresarial'),
					('$id_empresa', 527003, 'VARIACIONES EN CIIF','$idGrupoEmpresarial'),
					('$id_empresa', 5275, 'PERDIDA METODO DE PARTICIPACION','$idGrupoEmpresarial'),
					('$id_empresa', 5280, 'DIVERSOS','$idGrupoEmpresarial'),
					('$id_empresa', 528005, 'COMISIONES','$idGrupoEmpresarial'),
					('$id_empresa', 528010, 'LIBROS, SUSCRIPCIONES,PERIODICOS Y REVIS','$idGrupoEmpresarial'),
					('$id_empresa', 528020, 'GASTOS DE REPRESENTACION Y RELACIONES P.','$idGrupoEmpresarial'),
					('$id_empresa', 528025, 'ELEMENTOS DE ASEO Y CAFETERIA','$idGrupoEmpresarial'),
					('$id_empresa', 528030, 'UTILES, PAPELERIA Y FOTOCOPIAS','$idGrupoEmpresarial'),
					('$id_empresa', 528035, 'COMBUSTIBLES Y LUBRICANTES','$idGrupoEmpresarial'),
					('$id_empresa', 528040, 'ENVASES Y EMPAQUES','$idGrupoEmpresarial'),
					('$id_empresa', 528045, 'TAXIS Y BUSES','$idGrupoEmpresarial'),
					('$id_empresa', 528050, 'ESTAMPILLAS','$idGrupoEmpresarial'),
					('$id_empresa', 528060, 'CASINO Y RESTAURANTE','$idGrupoEmpresarial'),
					('$id_empresa', 528065, 'PARQUEADEROS','$idGrupoEmpresarial'),
					('$id_empresa', 528095, 'OTROS','$idGrupoEmpresarial'),
					('$id_empresa', 5282, 'PROVISIONES','$idGrupoEmpresarial'),
					('$id_empresa', 528210, 'DEUDORES','$idGrupoEmpresarial'),
					('$id_empresa', 528220, 'PROPIEDADES PLANTA Y EQUIPO','$idGrupoEmpresarial'),
					('$id_empresa', 5285, 'FINANCIEROS','$idGrupoEmpresarial'),
					('$id_empresa', 528505, 'GASTOS BANCARIOS','$idGrupoEmpresarial'),
					('$id_empresa', 528515, 'COMISIONES','$idGrupoEmpresarial'),
					('$id_empresa', 528520, 'INTERESES','$idGrupoEmpresarial'),
					('$id_empresa', 528525, 'DIFERENCIA EN CAMBIO','$idGrupoEmpresarial'),
					('$id_empresa', 528526, 'DIFERENCIA EN CAMBIO NO REALIZADA','$idGrupoEmpresarial'),
					('$id_empresa', 528535, 'DESCUENTOS COMERCIALES CONDICIONADOS','$idGrupoEmpresarial'),
					('$id_empresa', 528595, 'OTROS','$idGrupoEmpresarial'),
					('$id_empresa', 5287, 'PERDIDA EN VENTA Y RETIRO DE BIENES','$idGrupoEmpresarial'),
					('$id_empresa', 528715, 'VENTA DE PROPIEDADES PLANTA Y EQUIPO','$idGrupoEmpresarial'),
					('$id_empresa', 528730, 'RETIRO PROPIEDAD PLANTA Y EQUIPO','$idGrupoEmpresarial'),
					('$id_empresa', 528735, 'RETIRO DE OTROS ACTIVOS','$idGrupoEmpresarial'),
					('$id_empresa', 528740, 'PERDIDAS POR SINIESTROS','$idGrupoEmpresarial'),
					('$id_empresa', 528795, 'PERDIDA ACTIVOS MOVILES HURTO(NO DEDUC)','$idGrupoEmpresarial'),
					('$id_empresa', 5290, 'GASTOS EXTRAORDINARIOS','$idGrupoEmpresarial'),
					('$id_empresa', 529005, 'COSTAS Y PROCESOS JUDICIALES','$idGrupoEmpresarial'),
					('$id_empresa', 529010, 'ACTIVIDADES CULTURALES Y CIVICAS','$idGrupoEmpresarial'),
					('$id_empresa', 529015, 'COSTOS Y GASTOS DE EJERCICIOS ANTERIORES','$idGrupoEmpresarial'),
					('$id_empresa', 529020, 'IMPUESTOS ASUMIDOS','$idGrupoEmpresarial'),
					('$id_empresa', 529025, 'AJUSTE AL PESO','$idGrupoEmpresarial'),
					('$id_empresa', 5295, 'GASTOS DIVERSOS','$idGrupoEmpresarial'),
					('$id_empresa', 529520, 'MULTAS, SANCIONES Y LITIGIOS','$idGrupoEmpresarial'),
					('$id_empresa', 529525, 'DONACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 529595, 'OTROS','$idGrupoEmpresarial'),
					('$id_empresa', 529598, 'GASTOS NO DEDUCIBLES','$idGrupoEmpresarial'),
					('$id_empresa', 59, 'CIERRE DE INGRESOS, GASTOS Y COSTOS','$idGrupoEmpresarial'),
					('$id_empresa', 5905, 'GANANCIAS Y PERDIDAS','$idGrupoEmpresarial'),
					('$id_empresa', 590505, 'GANANCIAS Y PERDIDAS','$idGrupoEmpresarial'),
					('$id_empresa', 6, 'COSTOS','$idGrupoEmpresarial'),
					('$id_empresa', 61, 'COSTOS DE VENTAS','$idGrupoEmpresarial'),
					('$id_empresa', 6105, 'AGRICULTURA, GANADERIA, CAZA Y SILVICULTURA','$idGrupoEmpresarial'),
					('$id_empresa', 6110, 'PESCA','$idGrupoEmpresarial'),
					('$id_empresa', 6115, 'EXPLOTACION DE MINAS Y CANTERAS','$idGrupoEmpresarial'),
					('$id_empresa', 6120, 'INDUSTRIAS MANUFACTURERAS','$idGrupoEmpresarial'),
					('$id_empresa', 612070, 'COSTO ELABORACION ARTICULOS ILUMINACION','$idGrupoEmpresarial'),
					('$id_empresa', 612071, 'POR DEVOLUCION/ANULACION PERIODO ANTER','$idGrupoEmpresarial'),
					('$id_empresa', 6125, 'SUMINISTROS DE ELECTRICIDAD, GAS Y AGUA','$idGrupoEmpresarial'),
					('$id_empresa', 6130, 'CONSTRUCCION','$idGrupoEmpresarial'),
					('$id_empresa', 6135, 'COMERCIO AL MAYOR Y AL POR MENOR','$idGrupoEmpresarial'),
					('$id_empresa', 613502, 'VENTA DE VEHICULOS AUTOMOTORES','$idGrupoEmpresarial'),
					('$id_empresa', 613504, 'MANTENIMIENTO, REPARACION Y LAVADO DE VEHICULOS AUTOMOTORES','$idGrupoEmpresarial'),
					('$id_empresa', 613506, 'VENTA DE PARTES, PIEZAS Y ACCESORIOS DE VEHICULOS AUTOMOTORES','$idGrupoEmpresarial'),
					('$id_empresa', 613508, 'VENTA DE COMBUSTIBLES SOLIDOS, LIQUIDOS, GASEOSOS','$idGrupoEmpresarial'),
					('$id_empresa', 613510, 'VENTA DE LUBRICANTES, ADITIVOS, LLANTAS Y LUJOS PARA AUTOMOTORES','$idGrupoEmpresarial'),
					('$id_empresa', 613512, 'VENTA A CAMBIO DE RETRIBUCION O POR CONTRATA','$idGrupoEmpresarial'),
					('$id_empresa', 613514, 'VENTA DE INSUMOS, MATERIAS PRIMAS AGROPECUARIAS Y FLORES','$idGrupoEmpresarial'),
					('$id_empresa', 613516, 'VENTA DE OTROS INSUMOS Y MATERIAS PRIMAS NO AGROPECUARIAS','$idGrupoEmpresarial'),
					('$id_empresa', 613518, 'VENTA DE ANIMALES VIVOS Y CUEROS','$idGrupoEmpresarial'),
					('$id_empresa', 613520, 'VENTA DE PRODUCTOS EN ALMACENES NO ESPECIALIZADOS','$idGrupoEmpresarial'),
					('$id_empresa', 613522, 'VENTA DE PRODUCTOS AGROPECUARIOS','$idGrupoEmpresarial'),
					('$id_empresa', 613524, 'VENTA DE PRODUCTOS TEXTILES, DE VESTIR, DE CUERO Y CALZADO','$idGrupoEmpresarial'),
					('$id_empresa', 613526, 'VENTA DE PAPEL Y CARTON','$idGrupoEmpresarial'),
					('$id_empresa', 613528, 'VENTA DE LIBROS, REVISTAS, ELEMENTOS DE PAPELERIA, UTILES Y TEXTOS ESCOLARES','$idGrupoEmpresarial'),
					('$id_empresa', 613530, 'VENTA DE JUEGOS, JUGUETES Y ARTICULOS DEPORTIVOS','$idGrupoEmpresarial'),
					('$id_empresa', 613532, 'VENTA DE INSTRUMENTOS QUIRURGICOS Y ORTOPEDICOS','$idGrupoEmpresarial'),
					('$id_empresa', 613534, 'VENTA DE ARTICULOS EN RELOJERIAS Y JOYERIAS','$idGrupoEmpresarial'),
					('$id_empresa', 613536, 'VENTA DE ELECTRODOMESTICOS Y MUEBLES','$idGrupoEmpresarial'),
					('$id_empresa', 613538, 'VENTA DE PRODUCTOS DE ASEO, FARMACEUTICOS, MEDICINALES, Y ARTICULOS DE TOCADOR','$idGrupoEmpresarial'),
					('$id_empresa', 613540, 'VENTA DE CUBIERTOS, VAJILLAS, CRISTALERIA, PORCELANAS, CERAMICAS Y OTROS ARTICULOS DE USO DOMESTICO','$idGrupoEmpresarial'),
					('$id_empresa', 613542, 'VENTA DE MATERIALES DE CONSTRUCCION, FONTANERIA Y CALEFACCION','$idGrupoEmpresarial'),
					('$id_empresa', 613544, 'VENTA DE PINTURAS Y LACAS','$idGrupoEmpresarial'),
					('$id_empresa', 613546, 'VENTA DE PRODUCTOS DE VIDRIOS Y MARQUETERIA','$idGrupoEmpresarial'),
					('$id_empresa', 613548, 'VENTA DE HERRAMIENTAS Y ARTICULOS DE FERRETERIA','$idGrupoEmpresarial'),
					('$id_empresa', 613550, 'VENTA DE QUIMICOS','$idGrupoEmpresarial'),
					('$id_empresa', 613552, 'VENTA DE PRODUCTOS INTERMEDIOS, DESPERDICIOS Y DESECHOS','$idGrupoEmpresarial'),
					('$id_empresa', 613554, 'VENTA DE MAQUINARIA, EQUIPO DE OFICINA Y PROGRAMAS DE COMPUTADOR','$idGrupoEmpresarial'),
					('$id_empresa', 613556, 'VENTA DE ARTICULOS EN CACHARRERIAS Y MISCELANEAS','$idGrupoEmpresarial'),
					('$id_empresa', 613558, 'VENTA DE INSTRUMENTOS MUSICALES','$idGrupoEmpresarial'),
					('$id_empresa', 613560, 'VENTA DE ARTICULOS EN CASAS DE EMPEÃ?O Y PRENDERIAS','$idGrupoEmpresarial'),
					('$id_empresa', 613562, 'VENTA DE EQUIPO FOTOGRAFICO','$idGrupoEmpresarial'),
					('$id_empresa', 613564, 'VENTA DE EQUIPO OPTICO Y DE PRECISION','$idGrupoEmpresarial'),
					('$id_empresa', 613566, 'VENTA DE EMPAQUES','$idGrupoEmpresarial'),
					('$id_empresa', 613568, 'VENTA DE EQUIPO PROFESIONAL Y CIENTIFICO','$idGrupoEmpresarial'),
					('$id_empresa', 613570, 'VENTA DE LOTERIAS, RIFAS, CHANCE, APUESTAS Y SIMILARES','$idGrupoEmpresarial'),
					('$id_empresa', 613572, 'REPARACION DE EFECTOS PERSONALES Y ELECTRODOMESTICOS','$idGrupoEmpresarial'),
					('$id_empresa', 613595, 'VENTA DE OTROS PRODUCTOS','$idGrupoEmpresarial'),
					('$id_empresa', 613599, 'AJUSTES POR INFLACION','$idGrupoEmpresarial'),
					('$id_empresa', 6140, 'HOTELES Y RESTAURANTES','$idGrupoEmpresarial'),
					('$id_empresa', 6145, 'TRANSPORTE, ALMACENAMIENTO Y COMUNICACIONES','$idGrupoEmpresarial'),
					('$id_empresa', 6150, 'ACTIVIDAD FINANCIERA','$idGrupoEmpresarial'),
					('$id_empresa', 6155, 'ACTIVIDADES INMOBILIARIAS, EMPRESARIALES Y DE ALQUILER','$idGrupoEmpresarial'),
					('$id_empresa', 6160, 'ENSEÑANZAS','$idGrupoEmpresarial'),
					('$id_empresa', 6165, 'SERVICIOS SOCIALES Y DE SALUD','$idGrupoEmpresarial'),
					('$id_empresa', 6170, 'OTRAS ACTIVIDADES DE SERVICIOS COMUNITARIOS, SOCIALES Y PERSONALES','$idGrupoEmpresarial'),
					('$id_empresa', 7, 'COSTOS DE PRODUCCCION ','$idGrupoEmpresarial'),
					('$id_empresa', 71, 'COSTOS DE DISTRIBUCION ','$idGrupoEmpresarial'),
					('$id_empresa', 75, 'COSTOS FINANCIEROS','$idGrupoEmpresarial')";

// VALIDAR CANTIDAD DE CAMPOS POR INSERT EN PUC NIIF
/*$arraySqlPucNiif = explode('					(', $sqlPucNiif);
foreach ($arraySqlPucNiif as $variable) {
	$cont = substr_count($variable, "','");
	if($cont != 3) $error .= $variable.'</br>';
}*/
?>