<?php 
    //BARRA DE TAREAS
    $CONF_BARRATAREAS_UBICACION = 'abajo'; //'arriba' o 'abajo'
    $CONF_BARRATAREAS_ALTO = 28; // ALTO DE LA BARRA DE TAREAS

    //BOTON DE INICIO
    $CONF_BOTONINICIO_ALTO = 28; //ALTO DEL BOTON DE INICIO
    $CONF_BOTONINICIO_ANCHO = 60; // ANCHO DEL BOTON DE INICIO

    //BOTONES INICIO RAPIDO
    $CONF_INICIORAPIDO_ANCHO = 1; // ANHO DE LA BARRA DE BOTONES DE INICIO RAPIDO

    //BUSCADOR Y SYSTEM TRAY
    $CONF_SYSEMTRAY_ANCHO = 70; // ANCHO DEL SYSEM TRAY
    $CONF_SYSEMTRAY_RELOJ_ANCHO = 70; // ANCHO DEL RELOJ DEL SYSEM TRAY

    //TAMANOS DE LA VENTANA
    $margen_ventana = 10; //MARGEN DE LAS VENTANAS
    $CONF_BARRASUPERIOR_ALTO = 29; //ALTO DE LA BARRA SUPERIOR DE LAS VENTANAS
    $CONF_BARRASUPERIOR_ANCHO = 20; // ANCHO DE LAS IMAGENES DEL LAS ESQUINAS DE LA BARRA SUPERIOR
    $CONF_BARRAINFERIOR_ALTO = 5;//ALTO DE LA BARRA INFERIOR DE LAS VENTANAS
    $CONF_BARRAINFERIOR_ANCHO = 20;// ANCHO DE LAS IMAGENES DEL LAS ESQUINAS DE LA BARRA INFERIOR
    $CONF_LATERAL_ANCHO= 5;//ANCHO DE LAS BARRAS LATERALES
?>
