<?php

	include("../configuracion/conectar.php");
	include("../configuracion/define_variables.php");
	$permiso_colgaap    = (user_permisos(77,'false') == 'true')? false : true;
	$permiso_niif       = (user_permisos(78,'false') == 'true')? false : true;
	$permiso_ventas     = (user_permisos(79,'false') == 'true')? false : true;
	$permiso_compras    = (user_permisos(80,'false') == 'true')? false : true;
	$permiso_tributario = (user_permisos(197,'false') == 'true')? false : true;
	$permiso_crm        = (user_permisos(217,'false') == 'true')? false : true;
	$permiso_graficas   = (user_permisos(218,'false') == 'true')? false : true;
	$permiso_empleados  = (user_permisos(225,'false') == 'true')? false : true;
	$permiso_inventario  = false ;

	$arrayHead[1] = array('text' => 'Contabilidad Colgaap',
						'iconCls' => 'contabilidad16',
						'scale' => 'small',
						'disabled' => $permiso_colgaap,
						'items' => array(
										1 => array('text' => 'Balance de Comprobacion',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/contabilidad/contabilidad_balance_comprobacion.php'),
										2 => array('text' => 'Estado de Resultado',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/contabilidad/contabilidad_estado_de_resultado.php'),
										3 => array('text' => 'Estado de Resultado por Centro de Costo',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/contabilidad/contabilidad_estado_de_resultado_ccos.php'),
										4 => array('text' => 'Balance General',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/contabilidad/contabilidad_balance_general.php'),
										5 => array('text' => 'Libro Mayor',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/contabilidad/contabilidad_libro_mayor.php'),
										6 => array('text' => 'Libro Auxiliar',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/contabilidad/contabilidad_libro_auxiliar.php'),
										7 => array('text' => 'Libro Diario',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/contabilidad/contabilidad_libro_diario.php'),
										// 7 => array('text' => 'Libro Inventario y Balance',
										// 			'informe' => '',
										// 			'iconCls' => 'informe0',
										// 			'activo' => 'true',
										// 			'url' => 'informes/contabilidad/contabilidad_inventario_balance.php'),
										// 8 => array('text' => 'Costos ',
										// 			'informe' => '',
										// 			'iconCls' => 'informe0',
										// 			'activo' => 'true',
										// 			'url' => 'informes/contabilidad/contabilidad_costos.php'),
										8 => array('text' => 'Impuestos y Retenciones',
													'informe' => '',
													'iconCls' => 'ventas16',
													'activo' => 'true',
													'url' => 'informes/contabilidad/impuestos_retenciones.php'),
										9 => array('text' => 'ERP-Report',
													'informe' => '',
													'iconCls' => 'report',
													'activo' => 'true',
													'url' => 'informes/report/report.php'),
										10 => array('text' => 'Libro Inventario y Balance',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/contabilidad/contabilidad_inventario_balance.php'),
										11 => array('text' => 'Documentos Auditados',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/contabilidad/documentos_auditados.php'),
							)
						);

	$arrayHead[2] = array('text' => 'Contabilidad Niif',
						'iconCls' => 'contabilidad16',
						'scale' => 'small',
						'disabled' => $permiso_niif,
						'items' => array(
										1 => array('text' => 'Balance Comprobacion',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/contabilidad_niif/contabilidad_balance_comprobacion.php'),
										2 => array('text' => 'Libro Auxiliar',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/contabilidad_niif/contabilidad_libro_auxiliar.php'),
										// $informes,
										// 1 => array('text' => 'Estado Situacion Financiera',
										// 			'informe' => '',
										// 			'iconCls' => 'informe0',
										// 			'activo' => 'true',
										// 			'url' => 'informes/contabilidad_niif/estado_situacion_financiera.php'),
										// 2 => array('text' => 'Estado Resultados',
										// 			'informe' => '',
										// 			'iconCls' => 'informe0',
										// 			'activo' => 'true',
										// 			'url' => 'informes/contabilidad_niif/contabilidad_estado_de_resultado.php'),
										// 3 => array('text' => 'Estado Flujo Efectivo',
										// 			'informe' => '',
										// 			'iconCls' => 'informe0',
										// 			'activo' => 'true',
										// 			'url' => 'informes/contabilidad_niif/contabilidad_estado_flujo_efectivo.php'),
										)
						);

	$sql = "SELECT id,codigo,nombre FROM informes_niif_formatos WHERE activo = 1 AND id_empresa = " . $_SESSION['EMPRESA'];
	$query = $mysql->query($sql,$mysql->link);
	$posicion = 3;
	while($row = $mysql->fetch_array($query)){
		$arrayHead[2]['items'][$posicion] = array(
																								'id'      => $row['id'],
																								'codigo'  => $row['codigo'],
																								'text'    => $row['nombre'],
																								'informe' => '',
																								'iconCls' => 'informe0',
																								'activo'  => 'true',
																								'url'     => 'informes/contabilidad_niif/report_niif/report.php'
																							);
		$posicion++;
	}

	$arrayHead[3] = array(
						'text'     => 'Tributario',
						'iconCls'  => 'coins16',
						'scale'    => 'small',
						'disabled' => $permiso_tributario,
						'items'    => array(

										1 => array('text' => 'Ingresos y retenciones empleados',
													'informe' => '',
													'iconCls' => 'userTributario16',
													'activo' => 'true',
													'url' => 'informes/tributario/certificado_ingresos_retenciones.php'),

										2 => array('text' => 'Certificado Retencion ICA',
													'informe' => '',
													'iconCls' => 'certificado_16',
													'activo' => 'true',
													'url' => 'informes/tributario/certificado_retencion_ica.php'),

										3 => array('text' => 'Certificado Retencion en la Fuente',
													'informe' => '',
													'iconCls' => 'certificado_16',
													'activo' => 'true',
													'url' => 'informes/tributario/certificado_retencion_fuente.php'),

										4 => array('text' => 'Medios Magneticos',
													'informe' => '',
													'iconCls' => 'medios',
													'activo' => 'true',
													'url' => 'informes/tributario/contabilidad_medios_magneticos.php'),
										)
						);

	$arrayHead[4] = array(
						'text'     => 'Ventas',
						'iconCls'  => 'ventas16',
						'scale'    => 'small',
						'disabled' => $permiso_ventas,
						'items'    => array(
											1 => array('text' => 'Clientes',
														'informe' => '',
														'iconCls' => 'informe0',
														'activo'  => 'false',
														'url' => 'informes/informes_ventas/clientes.php'),
											2 => array('text' => 'Vendedores',
														'informe' => '',
														'iconCls' => 'informe0',
														'activo' => 'false',
														'url' => 'informes/informes_ventas/vendedores.php'),
											3 => array('text' => 'Cartera',
														'informe' => '',
														'iconCls' => 'informe0',
														'activo' => 'true',
														'url' => 'informes/informes_ventas/cartera_edades.php'),
											4 => array('text' => 'Estado De Cuenta',
														'informe' => '',
														'iconCls' => 'informe0',
														'activo' => 'true',
														'url' => 'informes/informes_ventas/estado_cuenta.php'),
											5 => array('text' => 'Facturas Radicadas',
														'informe' => '',
														'iconCls' => 'informe0',
														'activo' => 'true',
														'url' => 'informes/informes_ventas/facturas_radicadas.php'),
											6 => array('text' => 'Punto De Venta (POS)',
														'informe' => '',
														'iconCls' => 'informe0',
														'activo' => 'true',
														'url' => 'informes/pos/pos.php'),
											7 => array('text' => 'Cotizaciones',
														'informe' => '',
														'iconCls' => 'informe0',
														'activo' => 'true',
														'url' => 'informes/informes_ventas/cotizaciones.php'),
											8 => array('text' => 'Pedidos',
														'informe' => '',
														'iconCls' => 'informe0',
														'activo' => 'true',
														'url' => 'informes/informes_ventas/pedidos.php'),
											9 => array('text' => 'Remisiones',
														'informe' => '',
														'iconCls' => 'informe0',
														'activo' => 'true',
														'url' => 'informes/informes_ventas/remisiones.php'),
											10 => array('text' => 'Facturas',
														'informe' => '',
														'iconCls' => 'informe0',
														'activo' => 'true',
														'url' => 'informes/informes_ventas/facturas.php'),
											11 => array('text' => 'Facturas Por Cuentas',
														'informe' => '',
														'iconCls' => 'informe0',
														'activo' => 'true',
														'url' => 'informes/informes_ventas/facturas_por_cuentas.php'),
											12 => array('text' => 'Facturas Por Periodo',
														'informe' => '',
														'iconCls' => 'informe0',
														'activo' => 'true',
														'url' => 'informes/informes_ventas/facturas_por_periodo.php'),
											13 => array('text' => 'Facturas Archivos Adjuntos',
														'informe' => '',
														'iconCls' => 'informe0',
														'activo' => 'true',
														'url' => 'informes/informes_ventas/facturas_archivos_adjuntos.php'),
											14 => array('text' => 'Impuestos Y Retenciones',
														'informe' => '',
														'iconCls' => 'informe0',
														'activo' => 'true',
														'url' => 'informes/informes_ventas/impuestos_retenciones.php'),
											15 => array('text' => 'Recibos De Caja',
														'informe' => '',
														'iconCls' => 'informe0',
														'activo' => 'true',
														'url' => 'informes/informes_ventas/recibos_caja.php'),
											16 => array('text' => 'Devoluciones',
														'informe' => '',
														'iconCls' => 'informe0',
														'activo' => 'true',
														'url' => 'informes/informes_ventas/devoluciones.php'),
											17 => array('text' => 'Recibo De Caja Archivos Adjuntos',
														'informe' => '',
														'iconCls' => 'informe0',
														'activo' => 'true',
														'url' => 'informes/informes_ventas/recibos_caja_archivos_adjuntos.php'),
										)
						);

	$arrayHead[5] = array(
						'text'     => 'Compras',
						'iconCls'  => 'ventas16',
						'scale'    => 'small',
						'disabled' => $permiso_compras,
						'items'    => array(
										1 => array('text' => 'Facturas Por Pagar',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/contabilidad/contabilidad_facturas_por_pagar.php'),
													//'url' => 'informes/informes_compras/facturas_por_pagar.php'),
										2 => array('text' => 'Requisiciones',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/informes_compras/requisiciones.php'),
										3 => array('text' => 'Ordenes',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/informes_compras/ordenes.php'),
										4 => array('text' => 'Facturas',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/informes_compras/facturas.php'),
										5 => array('text' => 'Impuestos y Retenciones',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/informes_compras/impuestos_retenciones.php'),
										6 => array('text' => 'Comprobante Egreso',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/informes_compras/comprobante_egreso.php'),
										7 => array('text' => 'Comprobante Egreso Archivos Adjuntos',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/informes_compras/comprobante_egreso_archivos_adjuntos.php'),
										8 => array('text' => 'Devoluciones',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/informes_compras/devoluciones.php'),
										9 => array('text' => 'Factura De Compra Archivos Adjuntos',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/informes_compras/factura_compra_archivos_adjuntos.php'),
										10 => array('text' => 'Entrada Almacen',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/informes_compras/entrada_almacen.php'),
										11 => array('text' => 'Ordenes De Compra Archivos Adjuntos',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/informes_compras/ordenes_compra_archivos_adjuntos.php'),
										),
						);

	$arrayHead[6] = array(
						'text'     => 'CRM',
						'iconCls'  => 'informe0',
						'scale'    => 'small',
						'disabled' => $permiso_crm,
						'items'    => array(
										1 => array('text' => 'Formato de Visitas',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/crm/formato_visitas.php'),
										// 2 => array('text' => 'Formato de Clientes',
										// 			'informe' => '',
										// 			'iconCls' => 'informe0',
										// 			'activo' => 'true',
										// 			'url' => 'informes/crm/informe_de_clientes.php'),
										2 => array('text' => 'Informe de Objetivos',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/crm/informe_de_objetivos.php'),
										3 => array('text' => 'Informe de Prospectos',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/crm/informe_de_prospectos.php'),
										4 => array('text' => 'Informe de Clientes',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/crm/informe_de_clientes.php'),
										5 => array('text' => 'Informe de terceros',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/crm/terceros.php'),
										6 => array('text' => 'Informe de Actividades',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/crm/informe_de_actividades.php'),
										7 => array('text' => 'Informe de Contactos',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/crm/informe_de_terceros_contactos.php'),
										8 => array('text' => 'Informe Estadistico de Objetivos',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/crm/informe_de_objetivos_estadistico.php'),
										9 => array('text' => 'Informe De Objetivos Excel',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo' => 'true',
													'url' => 'informes/crm/informe_de_objetivos_listado.php'),


										)
						);

	$arrayHead[7] = array(
						'text'     => 'Graficos',
						'iconCls'  => 'informe4',
						'scale'    => 'small',
						'disabled' => $permiso_graficas,
						'items'    => array(
												1 => array(
													'text'    => 'Facturas de venta',
													'informe' => '',
													'iconCls' => 'informe0',
													'activo'  => 'true',
													'url'     => 'informes/graficos/informe_facturas_venta.php'),
												)
						);

	$arrayHead[8] = array(
						'text'     => 'Rec. Humanos',
						'iconCls'  => 'user16',
						'scale'    => 'small',
						'disabled' => $permiso_empleados,
						'items'    => array(
											1 => array(
														'text'    => 'Contratos',
														'informe' => '',
														'iconCls' => 'informe0',
														'activo'  => 'true',
														'url'     => 'informes/personal/contratos.php'
													),
											2 => array(
														'text'    => 'Empleados',
														'informe' => '',
														'iconCls' => 'informe0',
														'activo'  => 'true',
														'url'     => 'informes/personal/empleados.php'
													)
											)
						);

	$arrayHead[9] = array(
						  	'text'     => 'Inventario',
						  	'iconCls'  => 'inventario16',
						  	'scale'    => 'small',
							'disabled' => $permiso_inventario,
							'items'    => array(
												1  => array(
															'text'    => 'Items De Venta',
															'informe' => '',
															'iconCls' => 'informe0',
															'activo'  => 'true',
															'url'     => 'informes/informes_ventas/items.php'
															),
												2  => array(
															'text'    => 'Items Remisionados',
															'informe' => '',
															'iconCls' => 'informe0',
															'activo'  => 'true',
															'url'     => 'informes/informes_ventas/items_remisionados.php'
															),
												3  => array(
															'text'    => 'Inventario Consolidado',
															'informe' => '',
															'iconCls' => 'informe0',
															'activo'  => 'true',
															'url'     => 'informes/inventario/inventario_consolidado.php'
														    ),
												3  => array(
															'text'    => 'Inventario detalle costo',
															'informe' => '',
															'iconCls' => 'informe0',
															'activo'  => 'true',
															'url'     => 'informes/inventario/inventario_costo.php'
														    ),
												4  => array(
															'text'    => 'Kardex acumulado',
															'informe' => '',
															'iconCls' => 'inventario16',
															'activo'  => 'true',
															'url'     => 'informes/inventario/kardex/acumulado/frontend.php'
															),
											)
						);

?>
