<?php
	
	$arrayTablesData ['nomina_configuracion_tipo_documentos'] = "INSERT INTO nomina_configuracion_tipo_documentos (codigo,tipo,detalle,id_empresa) VALUES
																		('102','NominaIndividual','Documento Soporte de Pago de Nómina Electrónica',replace_SESSION_EMPRESA),
																		('103','NominaIndividualDeAjuste','Nota de Ajuste de Documento Soporte de Pago de Nómina Electrónica',replace_SESSION_EMPRESA)";

	$arrayTablesData ['nomina_configuracion_tipo_documentos_ajuste'] = "INSERT INTO nomina_configuracion_tipo_documentos_ajuste (codigo,nombre,id_empresa) VALUES
																			('1','Reemplazar',replace_SESSION_EMPRESA),
																			('2','Eliminar',replace_SESSION_EMPRESA) ";

	$arrayTablesData ['nomina_tipos_liquidacion'] = "INSERT INTO nomina_tipos_liquidacion (codigo,nombre,dias,id_empresa) VALUES 
														('1', 'Semanal',8,replace_SESSION_EMPRESA),
														('2', 'Decenal',10,replace_SESSION_EMPRESA),
														('3', 'Catorcenal',14,replace_SESSION_EMPRESA),
														('4', 'Quincenal',15,replace_SESSION_EMPRESA),
														('5', 'Mensual',30,replace_SESSION_EMPRESA),
														('6', 'Otro',0,replace_SESSION_EMPRESA)";

	$arrayTablesData ['nomina_tipo_contrato'] = "INSERT INTO nomina_tipo_contrato (codigo_dian,descripcion,id_empresa) VALUES 
																	('01', 'Termino Fijo',replace_SESSION_EMPRESA),
																	('02', 'Término Indefinido',replace_SESSION_EMPRESA),
																	('03', 'Obra o Labor',replace_SESSION_EMPRESA),
																	('04', 'Aprendizaje',replace_SESSION_EMPRESA),
																	('05', 'Prácticas o Pasantías',replace_SESSION_EMPRESA)";

	$arrayTablesData ['nomina_configuracion_tipo_trabajador'] = "INSERT INTO nomina_configuracion_tipo_trabajador (codigo,tipo,id_empresa) VALUES 
																	('01','Dependiente',replace_SESSION_EMPRESA),
																	('02','Servicio domestico',replace_SESSION_EMPRESA),
																	('04','Madre comunitaria',replace_SESSION_EMPRESA),
																	('12','Aprendices del Sena en etapa lectiva',replace_SESSION_EMPRESA),
																	('18','Funcionarios públicos sin tope máximo de ibc',replace_SESSION_EMPRESA),
																	('19','Aprendices del SENA en etapa productiva',replace_SESSION_EMPRESA),
																	('21','Estudiantes de postgrado en salud',replace_SESSION_EMPRESA),
																	('22','Profesor de establecimiento particular',replace_SESSION_EMPRESA),
																	('23','Estudiantes aportes solo riesgos laborales',replace_SESSION_EMPRESA),
																	('30','Dependiente entidades o universidades públicas con régimen especial en salud',replace_SESSION_EMPRESA),
																	('31','Cooperados o pre cooperativas de trabajo asociado',replace_SESSION_EMPRESA),
																	('47','Trabajador dependiente de entidad beneficiaria del sistema general de participaciones - aportes patronales',replace_SESSION_EMPRESA),
																	('51','Trabajador de tiempo parcial',replace_SESSION_EMPRESA),
																	('54','Pre pensionado de entidad en liquidación.',replace_SESSION_EMPRESA),
																	('56','Pre pensionado con aporte voluntario a salud',replace_SESSION_EMPRESA),
																	('58','Estudiantes de prácticas laborales en el sector público',replace_SESSION_EMPRESA)";



	$arrayTablesData ['nomina_configuracion_subtipo_trabajador'] = "INSERT INTO nomina_configuracion_subtipo_trabajador (codigo,tipo,id_empresa) VALUES
																	('00','No Aplica',replace_SESSION_EMPRESA),
																	('01','Dependiente pensionado por vejez activo',replace_SESSION_EMPRESA)";

	$arrayTablesData ['nomina_configuracion_formas_pago'] = "INSERT INTO nomina_configuracion_formas_pago (codigo,nombre,id_empresa) VALUES 
																(1,'Contado',replace_SESSION_EMPRESA)";

	$arrayTablesData ['nomina_configuracion_medios_pago'] = "INSERT INTO nomina_configuracion_medios_pago (codigo,nombre,id_empresa) VALUES 
																('1','Instrumento no definido',replace_SESSION_EMPRESA),
																('2','Crédito ACH',replace_SESSION_EMPRESA),
																('3','Débito ACH',replace_SESSION_EMPRESA),
																('4','Reversión débito de demanda ACH',replace_SESSION_EMPRESA),
																('5','Reversión crédito de demanda ACH',replace_SESSION_EMPRESA),
																('6','Crédito de demanda ACH',replace_SESSION_EMPRESA),
																('7','Débito de demanda ACH',replace_SESSION_EMPRESA),
																('8','Mantener',replace_SESSION_EMPRESA),
																('9','Clearing Nacional o Regional',replace_SESSION_EMPRESA),
																('10','Efectivo',replace_SESSION_EMPRESA),
																('11','Reversión Crédito Ahorro',replace_SESSION_EMPRESA),
																('12','Reversión Débito Ahorro',replace_SESSION_EMPRESA),
																('13','Crédito Ahorro',replace_SESSION_EMPRESA),
																('14','Débito Ahorro',replace_SESSION_EMPRESA),
																('15','Bookentry Crédito',replace_SESSION_EMPRESA),
																('16','Bookentry Débito',replace_SESSION_EMPRESA),
																('17','Concentración de la demanda en efectivo Desembolso Crédito (CCD)',replace_SESSION_EMPRESA),
																('18','Concentración de la demanda en efectivo / Desembolso (CCD) débito',replace_SESSION_EMPRESA),
																('19','Crédito Pago negocio corporativo (CTP)',replace_SESSION_EMPRESA),
																('20','Cheque',replace_SESSION_EMPRESA),
																('21','Proyecto bancario',replace_SESSION_EMPRESA),
																('22','Proyecto bancario certificado',replace_SESSION_EMPRESA),
																('23','Cheque bancario',replace_SESSION_EMPRESA),
																('24','Nota cambiaria esperando aceptación',replace_SESSION_EMPRESA),
																('25','Cheque certificado',replace_SESSION_EMPRESA),
																('26','Cheque Local',replace_SESSION_EMPRESA),
																('27','Débito Pago Negocio Corporativo (CTP)',replace_SESSION_EMPRESA),
																('28','Crédito Negocio Intercambio Corporativo (CTX)',replace_SESSION_EMPRESA),
																('29','Débito Negocio Intercambio Corporativo (CTX)',replace_SESSION_EMPRESA),
																('30','Transferencia Crédito',replace_SESSION_EMPRESA),
																('31','Transferencia Débito',replace_SESSION_EMPRESA),
																('32','Concentración Efectivo / Desembolso Crédito plus (CCD+)',replace_SESSION_EMPRESA),
																('33','Concentración Efectivo / Desembolso Débito plus (CCD+)',replace_SESSION_EMPRESA),
																('34','Pago y depósito pre acordado (PPD)',replace_SESSION_EMPRESA),
																('35','Concentración efectivo ahorros / Desembolso Crédito (CCD)',replace_SESSION_EMPRESA),
																('36','Concentración efectivo ahorros / Desembolso Crédito (CCD)',replace_SESSION_EMPRESA),
																('37','Pago Negocio Corporativo Ahorros Crédito (CTP)',replace_SESSION_EMPRESA),
																('38','Pago Negocio Corporativo Ahorros Débito (CTP)',replace_SESSION_EMPRESA),
																('39','Crédito Negocio Intercambio Corporativo (CTX)',replace_SESSION_EMPRESA),
																('40','Débito Negocio Intercambio Corporativo (CTX)',replace_SESSION_EMPRESA),
																('41','Concentración efectivo/Desembolso Crédito plus (CCD+)',replace_SESSION_EMPRESA),
																('42','Consignación bancaria',replace_SESSION_EMPRESA),
																('43','Concentración efectivo / Desembolso Débito plus (CCD+)',replace_SESSION_EMPRESA),
																('44','Nota cambiaria',replace_SESSION_EMPRESA),
																('45','Transferencia Crédito Bancario',replace_SESSION_EMPRESA),
																('46','Transferencia Débito Interbancario',replace_SESSION_EMPRESA),
																('47','Transferencia Débito Bancaria',replace_SESSION_EMPRESA),
																('48','Tarjeta Crédito',replace_SESSION_EMPRESA),
																('49','Tarjeta Débito',replace_SESSION_EMPRESA),
																('50','Postgiro',replace_SESSION_EMPRESA),
																('51','Telex estándar bancario francés',replace_SESSION_EMPRESA),
																('52','Pago comercial urgente',replace_SESSION_EMPRESA),
																('53','Pago Tesorería Urgente',replace_SESSION_EMPRESA),
																('60','Nota promisoria',replace_SESSION_EMPRESA),
																('61','Nota promisoria firmada por el acreedor',replace_SESSION_EMPRESA),
																('62','Nota promisoria firmada por el acreedor, avalada por el banco',replace_SESSION_EMPRESA),
																('63','Nota promisoria firmada por el acreedor, avalada por un tercero',replace_SESSION_EMPRESA),
																('64','Nota promisoria firmada por el banco',replace_SESSION_EMPRESA),
																('65','Nota promisoria firmada por un banco avalada por otro banco',replace_SESSION_EMPRESA),
																('66','Nota promisoria firmada',replace_SESSION_EMPRESA),
																('67','Nota promisoria firmada por un tercero avalada por un banco',replace_SESSION_EMPRESA),
																('70','Retiro de nota por el por el acreedor',replace_SESSION_EMPRESA),
																('71','Bonos',replace_SESSION_EMPRESA),
																('72','Vales',replace_SESSION_EMPRESA),
																('74','Retiro de nota por el por el acreedor sobre un banco',replace_SESSION_EMPRESA),
																('75','Retiro de nota por el acreedor, avalada por otro banco',replace_SESSION_EMPRESA),
																('76','Retiro de nota por el acreedor, sobre un banco avalada por un tercero',replace_SESSION_EMPRESA),
																('77','Retiro de una nota por el acreedor sobre un tercero',replace_SESSION_EMPRESA),
																('78','Retiro de una nota por el acreedor sobre un tercero avalada por un banco',replace_SESSION_EMPRESA),
																('91','Nota bancaria transferible',replace_SESSION_EMPRESA),
																('92','Cheque local trasferible',replace_SESSION_EMPRESA),
																('93','Giro referenciado',replace_SESSION_EMPRESA),
																('94','Giro urgente',replace_SESSION_EMPRESA),
																('95','Giro formato abierto',replace_SESSION_EMPRESA),
																('96','Método de pago solicitado no usado',replace_SESSION_EMPRESA),
																('97','Clearing entre partners',replace_SESSION_EMPRESA),
																('98','Cuentas de Ahorro de Tramite Simplificado (CATS)(Nequi, Daviplata, etc)',replace_SESSION_EMPRESA),
																('ZZZ','Acuerdo mutuo',replace_SESSION_EMPRESA)
																";

	$arrayTablesData ['nomina_configuracion_hora_extra_recargo'] = "";

	$arrayTablesData ['nomina_configuracion_idiomas'] = "INSERT INTO nomina_configuracion_idiomas (nombre,ISO_639_1,ISO_639_2,id_empresa) VALUES
																('Abkhaz','ab','abk',replace_SESSION_EMPRESA),
																('Afar','aa','aar',replace_SESSION_EMPRESA),
																('Africanos','af','afr',replace_SESSION_EMPRESA),
																('Akan','ak','aka',replace_SESSION_EMPRESA),
																('Albania','sq','sqi',replace_SESSION_EMPRESA),
																('Amárico','am','amh',replace_SESSION_EMPRESA),
																('Árabe','ar','ara',replace_SESSION_EMPRESA),
																('Aragonés','an','arg',replace_SESSION_EMPRESA),
																('Armenio','hy','hye',replace_SESSION_EMPRESA),
																('Assamese','los','asm',replace_SESSION_EMPRESA),
																('Avaric','av','ava',replace_SESSION_EMPRESA),
																('Avestan','ae','ave',replace_SESSION_EMPRESA),
																('Aymara','ay','aym',replace_SESSION_EMPRESA),
																('Azerbaiyán','az','aze',replace_SESSION_EMPRESA),
																('Bambara','bm','bam',replace_SESSION_EMPRESA),
																('Bashkir','ba','bak',replace_SESSION_EMPRESA),
																('Vasco','eu','eus',replace_SESSION_EMPRESA),
																('Belarús','be','bel',replace_SESSION_EMPRESA),
																('Bengalí','bn','ben',replace_SESSION_EMPRESA),
																('Bihari','bh','bih',replace_SESSION_EMPRESA),
																('Bislama','bi','bis',replace_SESSION_EMPRESA),
																('Bosnia','bs','bos',replace_SESSION_EMPRESA),
																('Breton','br','bre',replace_SESSION_EMPRESA),
																('Búlgaro','bg','bul',replace_SESSION_EMPRESA),
																('Burmese','my','mya',replace_SESSION_EMPRESA),
																('Catalán','ca','cat',replace_SESSION_EMPRESA),
																('Chamorro','ch','cha',replace_SESSION_EMPRESA),
																('Chechenio','ce','che',replace_SESSION_EMPRESA),
																('Chichewa, Chewa, Nyanja','ny','nya',replace_SESSION_EMPRESA),
																('Chino','zh','zho',replace_SESSION_EMPRESA),
																('Chuvashia','cv','chv',replace_SESSION_EMPRESA),
																('Cornualles','kw','cor',replace_SESSION_EMPRESA),
																('Corso','co','cos',replace_SESSION_EMPRESA),
																('Cree','cr','cre',replace_SESSION_EMPRESA),
																('Croacia','hr','hrv',replace_SESSION_EMPRESA),
																('Checo','cs','ces',replace_SESSION_EMPRESA),
																('Danés','da','dan',replace_SESSION_EMPRESA),
																('Divehi, Dhivehi, Maldivas','dv','div',replace_SESSION_EMPRESA),
																('Holandés','nl','nld',replace_SESSION_EMPRESA),
																('Dzongkha','dz','dzo',replace_SESSION_EMPRESA),
																('Inglés','en','eng',replace_SESSION_EMPRESA),
																('Esperanto','eo','epo',replace_SESSION_EMPRESA),
																('Estonia','et','est',replace_SESSION_EMPRESA),
																('Ewe','ee','ewe',replace_SESSION_EMPRESA),
																('Faroese','fo','fao',replace_SESSION_EMPRESA),
																('Fiji','fj','fij',replace_SESSION_EMPRESA),
																('Finlandés','fi','fin',replace_SESSION_EMPRESA),
																('Francés','fr','fra',replace_SESSION_EMPRESA),
																('Fula, Fulah, Pulaar, Pular','ff','ful',replace_SESSION_EMPRESA),
																('Galicia','gl','glg',replace_SESSION_EMPRESA),
																('Georgiano','ka','kat',replace_SESSION_EMPRESA),
																('Alemán','de','deu',replace_SESSION_EMPRESA),
																('Griego Moderno','el','ell',replace_SESSION_EMPRESA),
																('Guaraní','gn','grn',replace_SESSION_EMPRESA),
																('Gujarati','gu','guj',replace_SESSION_EMPRESA),
																('Haitiano, creole haitiano','ht','hat',replace_SESSION_EMPRESA),
																('Hausa','ha','hau',replace_SESSION_EMPRESA),
																('Hebreo (moderno)','he','heb',replace_SESSION_EMPRESA),
																('Herero','hz','her',replace_SESSION_EMPRESA),
																('Hindi','hi','hin',replace_SESSION_EMPRESA),
																('Hiri Motu','ho','hmo',replace_SESSION_EMPRESA),
																('Húngaro','hu','hun',replace_SESSION_EMPRESA),
																('Interlingua','ia','ina',replace_SESSION_EMPRESA),
																('Indonesio','id','ind',replace_SESSION_EMPRESA),
																('Interlingue','ie','ile',replace_SESSION_EMPRESA),
																('Irlanda','ga','gle',replace_SESSION_EMPRESA),
																('Igbo','ig','ibo',replace_SESSION_EMPRESA),
																('Inupiaq','ik','ipk',replace_SESSION_EMPRESA),
																('Ido','io','ido',replace_SESSION_EMPRESA),
																('Islandés','is','isl',replace_SESSION_EMPRESA),
																('Italiano','it','ita',replace_SESSION_EMPRESA),
																('Inuktitut','iu','iku',replace_SESSION_EMPRESA),
																('Japonés','ja','jpn',replace_SESSION_EMPRESA),
																('Javanés','jv','jav',replace_SESSION_EMPRESA),
																('Kalaallisut, Groenlandia','kl','kal',replace_SESSION_EMPRESA),
																('Canarés','kn','kan',replace_SESSION_EMPRESA),
																('Kanuri','kr','kau',replace_SESSION_EMPRESA),
																('Cachemira','ks','kas',replace_SESSION_EMPRESA),
																('Kazajstán','kk','kaz',replace_SESSION_EMPRESA),
																('Khmer','km','khm',replace_SESSION_EMPRESA),
																('Kikuyu, Gikuyu','ki','kik',replace_SESSION_EMPRESA),
																('Kinyarwanda','rw','kin',replace_SESSION_EMPRESA),
																('Kirguises, Kirguistán','ky','kir',replace_SESSION_EMPRESA),
																('Komi','kv','kom',replace_SESSION_EMPRESA),
																('Kongo','kg','kon',replace_SESSION_EMPRESA),
																('Corea','ko','kor',replace_SESSION_EMPRESA),
																('Kurdo','ku','kur',replace_SESSION_EMPRESA),
																('Kwanyama, Kuanyama','kj','kua',replace_SESSION_EMPRESA),
																('Latin','la','lat',replace_SESSION_EMPRESA),
																('Luxemburgués, Luxemburgués','lb','ltz',replace_SESSION_EMPRESA),
																('Luganda','lg','lug',replace_SESSION_EMPRESA),
																('Limburgués,Limburgan, Limburger','li','lim',replace_SESSION_EMPRESA),
																('Lingala','Ln','lin',replace_SESSION_EMPRESA),
																('Lao','Lo','lao',replace_SESSION_EMPRESA),
																('Lituano','Lt','lit',replace_SESSION_EMPRESA),
																('Luba-Katanga','Lu','lub',replace_SESSION_EMPRESA),
																('Letonia','Lv','lav',replace_SESSION_EMPRESA),
																('Manx','Gv','glv',replace_SESSION_EMPRESA),
																('Macedonia','Mk','mkd',replace_SESSION_EMPRESA),
																('Madagascar','Mg','mlg',replace_SESSION_EMPRESA),
																('Malayo','Ms','msa',replace_SESSION_EMPRESA),
																('Malayalam','Ml','mal',replace_SESSION_EMPRESA),
																('Maltés','Mt','mlt',replace_SESSION_EMPRESA),
																('Māori','Mi','mri',replace_SESSION_EMPRESA),
																('Maratí (Marathi)','Mr','mar',replace_SESSION_EMPRESA),
																('De las Islas Marshall','Mh','mah',replace_SESSION_EMPRESA),
																('Mongolia','Mn','mon',replace_SESSION_EMPRESA),
																('Nauru','Na','nau',replace_SESSION_EMPRESA),
																('Navajo, Navaho','Nv','nav',replace_SESSION_EMPRESA),
																('Noruego Bokmål','Nb','nob',replace_SESSION_EMPRESA),
																('Ndebele del Norte','Nd','nde',replace_SESSION_EMPRESA),
																('Nepali','Ne','nep',replace_SESSION_EMPRESA),
																('Ndonga','Ng','ndo',replace_SESSION_EMPRESA),
																('Noruego Nynorsk','Nn','nno',replace_SESSION_EMPRESA),
																('Noruego','No','nor',replace_SESSION_EMPRESA),
																('Nuosu','Ii','iii',replace_SESSION_EMPRESA),
																('Ndebele del sur','nr','nbl',replace_SESSION_EMPRESA),
																('Occitano','oc','oci',replace_SESSION_EMPRESA),
																('Ojibwe, Ojibwa','oj','oji',replace_SESSION_EMPRESA),
																('Antiguo eslavo eclesiástico, Iglesia	eslava, eslavo eclesiástico, antiguo Búlgaro, Esclavo viejo','cu','chu',replace_SESSION_EMPRESA),
																('Oromo','om','orm',replace_SESSION_EMPRESA),
																('Oriya','or','ori',replace_SESSION_EMPRESA),
																('Osetia del Sur, osetio','os','oss',replace_SESSION_EMPRESA),
																('Panjabi, Punjabi','pa','pan',replace_SESSION_EMPRESA),
																('Pāli','pi','pli',replace_SESSION_EMPRESA),
																('Persa','fa','fas',replace_SESSION_EMPRESA),
																('Polaco','pl','pol',replace_SESSION_EMPRESA),
																('Pashto, Pushto','ps','pus',replace_SESSION_EMPRESA),
																('Portugués','pt','por',replace_SESSION_EMPRESA),
																('Quechua','qu','que',replace_SESSION_EMPRESA),
																('Romanche','rm','roh',replace_SESSION_EMPRESA),
																('Kirundi','rn','run',replace_SESSION_EMPRESA),
																('Rumania, Moldavia, Moldavan','ro','ron',replace_SESSION_EMPRESA),
																('Ruso','ru','rus',replace_SESSION_EMPRESA),
																('Sánscrito (samskrta)','sa','san',replace_SESSION_EMPRESA),
																('Sardo','sc','srd',replace_SESSION_EMPRESA),
																('Sindhi','sd','snd',replace_SESSION_EMPRESA),
																('Sami del norte','se','sme',replace_SESSION_EMPRESA),
																('Samoa','sm','smo',replace_SESSION_EMPRESA),
																('Sango','sg','sag',replace_SESSION_EMPRESA),
																('Serbio','sr','srp',replace_SESSION_EMPRESA),
																('Gaélico escocés, gaélico','gd','gla',replace_SESSION_EMPRESA),
																('Shona','sn','sna',replace_SESSION_EMPRESA),
																('Cingalés, singalés','si','sin',replace_SESSION_EMPRESA),
																('Eslovaca','sk','slk',replace_SESSION_EMPRESA),
																('Esloveno','sl','slv',replace_SESSION_EMPRESA),
																('Somalí','so','som',replace_SESSION_EMPRESA),
																('Southern Sotho','st','sot',replace_SESSION_EMPRESA),
																('Español, castellano','es','spa',replace_SESSION_EMPRESA),
																('Sundanese','su','sun',replace_SESSION_EMPRESA),
																('Swahili','sw','swa',replace_SESSION_EMPRESA),
																('Swati','ss','ssw',replace_SESSION_EMPRESA),
																('Sueco','sv','swe',replace_SESSION_EMPRESA),
																('Tamil','ta','tam',replace_SESSION_EMPRESA),
																('Telugu','te','tel',replace_SESSION_EMPRESA),
																('Tayikistán','tg','tgk',replace_SESSION_EMPRESA),
																('Tailandia','th','tha',replace_SESSION_EMPRESA),
																('Tigrinya','ti','tir',replace_SESSION_EMPRESA),
																('Tibetano estándar, Tibetano, Central','bo','bod',replace_SESSION_EMPRESA),
																('Turkmenistán','tk','tuk',replace_SESSION_EMPRESA),
																('Tagalo','tl','tgl',replace_SESSION_EMPRESA),
																('Tswana','tn','tsn',replace_SESSION_EMPRESA),
																('Tonga (Islas Tonga)','to','ton',replace_SESSION_EMPRESA),
																('Turco','tr','tur',replace_SESSION_EMPRESA),
																('Tsonga','ts','tso',replace_SESSION_EMPRESA),
																('Tártara','tt','tat',replace_SESSION_EMPRESA),
																('Twi','tw','twi',replace_SESSION_EMPRESA),
																('Tahitian','ty','tah',replace_SESSION_EMPRESA),
																('Uighur, Uyghur','ug','uig',replace_SESSION_EMPRESA),
																('Ucrania','uk','ukr',replace_SESSION_EMPRESA),
																('Urdu','ur','urd',replace_SESSION_EMPRESA),
																('Uzbeko','uz','uzb',replace_SESSION_EMPRESA),
																('Venda','ve','ven',replace_SESSION_EMPRESA),
																('Vietnamita','vi','vie',replace_SESSION_EMPRESA),
																('Volapük','vo','vol',replace_SESSION_EMPRESA),
																('Valonia','wa','wln',replace_SESSION_EMPRESA),
																('Galés','cy','cym',replace_SESSION_EMPRESA),
																('Wolof','wo','wol',replace_SESSION_EMPRESA),
																('Oeste de Frisia','fy','fry',replace_SESSION_EMPRESA),
																('Xhosa','xh','xho',replace_SESSION_EMPRESA),
																('Yiddish','yi','yid',replace_SESSION_EMPRESA),
																('Yoruba','yo','yor',replace_SESSION_EMPRESA),
																('Zhuang, Chuang','za','zha',replace_SESSION_EMPRESA),
																('Zulu','zu','zul',replace_SESSION_EMPRESA)";

	$arrayTablesData ['nomina_configuracion_monedas'] = "INSERT INTO nomina_configuracion_monedas (codigo,divisa,pais,id_empresa) VALUES
															('AED','Dírham de los Emiratos Árabes Unidos','Emiratos Árabes Unidos',replace_SESSION_EMPRESA),
															('AFN','Afgani','Afganistán',replace_SESSION_EMPRESA),
															('ALL','Lek','Albania',replace_SESSION_EMPRESA),
															('AMD','Dram armenio','Armenia',replace_SESSION_EMPRESA),
															('ANG','Florín antillano neerlandés','Curazao, Saint Maarten',replace_SESSION_EMPRESA),
															('AOA','Kwanza','Angola',replace_SESSION_EMPRESA),
															('ARS','Peso argentino','Argentina',replace_SESSION_EMPRESA),
															('AUD','Dólar australiano','Australia, Isla de Navidad, Islas Cocos, Islas Heard y McDonald, Kiribati, Nauru, Norfolk, Tuvalu',replace_SESSION_EMPRESA),
															('AWG','Florín arubeño','Aruba',replace_SESSION_EMPRESA),
															('AZN','Manat azerbaiyano','Azerbaiyán',replace_SESSION_EMPRESA),
															('BAM','Marco convertible','Bosnia y Herzegovina',replace_SESSION_EMPRESA),
															('BBD','Dólar de Barbados','Barbados',replace_SESSION_EMPRESA),
															('BDT','Taka','Bangladés',replace_SESSION_EMPRESA),
															('BGN','Lev búlgaro','Bulgaria',replace_SESSION_EMPRESA),
															('BHD','Dinar bareiní','Baréin',replace_SESSION_EMPRESA),
															('BIF','Franco de Burundi','Burundi',replace_SESSION_EMPRESA),
															('BMD','Dólar bermudeño','Bermudas',replace_SESSION_EMPRESA),
															('BND','Dólar de Brunéi','Brunéi',replace_SESSION_EMPRESA),
															('BOB','Boliviano','Bolivia',replace_SESSION_EMPRESA),
															('BOV','MVDOL','Bolivia',replace_SESSION_EMPRESA),
															('BRL','Real brasileño','Brasil',replace_SESSION_EMPRESA),
															('BSD','Dólar bahameño','Bahamas',replace_SESSION_EMPRESA),
															('BTN','Ngultrum','Bután',replace_SESSION_EMPRESA),
															('BWP','Pula','Botsuana',replace_SESSION_EMPRESA),
															('BYR','Rublo bielorruso','Bielorrusia',replace_SESSION_EMPRESA),
															('BZD','Dólar beliceño','Belice',replace_SESSION_EMPRESA),
															('CAD','Dólar canadiense','Canadá',replace_SESSION_EMPRESA),
															('CDF','Franco congoleño','República Democrática del Congo',replace_SESSION_EMPRESA),
															('CHE','Euro WIR','Suiza',replace_SESSION_EMPRESA),
															('CHF','Franco suizo','Liechtenstein, Suiza',replace_SESSION_EMPRESA),
															('CHW','Franco WIR','Suiza',replace_SESSION_EMPRESA),
															('CLF','Unidad de fomento','Chile',replace_SESSION_EMPRESA),
															('CLP','Peso chileno','Chile',replace_SESSION_EMPRESA),
															('CNY','Yuan chino','China',replace_SESSION_EMPRESA),
															('COP','Peso colombiano','Colombia',replace_SESSION_EMPRESA),
															('COU','Unidad de valor real','Colombia',replace_SESSION_EMPRESA),
															('CRC','Colón costarricense','Costa Rica',replace_SESSION_EMPRESA),
															('CUC','Peso convertible','Cuba',replace_SESSION_EMPRESA),
															('CUP','Peso cubano','Cuba',replace_SESSION_EMPRESA),
															('CVE','Escudo caboverdiano','Cabo Verde',replace_SESSION_EMPRESA),
															('CZK','Corona checa','República Checa',replace_SESSION_EMPRESA),
															('DJF','Franco yibutiano','Yibuti',replace_SESSION_EMPRESA),
															('DKK','Corona danesa','Dinamarca, Groenlandia, Islas Feroe',replace_SESSION_EMPRESA),
															('DOP','Peso dominicano','República Dominicana',replace_SESSION_EMPRESA),
															('DZD','Dinar argelino','Argelia',replace_SESSION_EMPRESA),
															('EGP','Libra egipcia','Egipto',replace_SESSION_EMPRESA),
															('ERN','Nakfa','Eritrea',replace_SESSION_EMPRESA),
															('ETB','Birr etíope','Etiopía',replace_SESSION_EMPRESA),
															('EUR','Euro','Alemania, Andorra, Austria, Bélgica, Chipre, Ciudad del Vaticano, Eslovaquia, Eslovenia, España, Estonia, Finlandia, Francia, Grecia, Guadalupe, Guayana Francesa, Irlanda, Italia, Letonia, Lituania, Luxemburgo, Malta, Martinica, Mayotte, Mónaco, Montenegro, Países Bajos, Portugal, Reunión, San Bartolomé, San Marino, San Martín, San Pedro y Miquelón, Tierras Australes y Antárticas Francesas, Unión Europea',replace_SESSION_EMPRESA),
															('FJD','Dólar fiyiano','Fiyi',replace_SESSION_EMPRESA),
															('FKP','Libra malvinense','Islas Malvinas',replace_SESSION_EMPRESA),
															('GBP','Libra esterlina','Guernsey, Isla de Man, Jersey, Reino Unido',replace_SESSION_EMPRESA),
															('GEL','Lari','Georgia',replace_SESSION_EMPRESA),
															('GHS','Cedi ghanés','Ghana',replace_SESSION_EMPRESA),
															('GIP','Libra de Gibraltar','Gibraltar',replace_SESSION_EMPRESA),
															('GMD','Dalasi','Gambia',replace_SESSION_EMPRESA),
															('GNF','Franco guineano','Guinea',replace_SESSION_EMPRESA),
															('GTQ','Quetzal','Guatemala',replace_SESSION_EMPRESA),
															('GYD','Dólar guyanés','Guyana',replace_SESSION_EMPRESA),
															('HKD','Dólar de Hong Kong','Hong Kong',replace_SESSION_EMPRESA),
															('HNL','Lempira','Honduras',replace_SESSION_EMPRESA),
															('HRK','Kuna','Croacia',replace_SESSION_EMPRESA),
															('HTG','Gourde','Haití',replace_SESSION_EMPRESA),
															('HUF','Forinto','Hungría',replace_SESSION_EMPRESA),
															('IDR','Rupia indonesia','Indonesia',replace_SESSION_EMPRESA),
															('ILS','Nuevo shéquel israelí','Israel',replace_SESSION_EMPRESA),
															('INR','Rupia india','Bután, India',replace_SESSION_EMPRESA),
															('IQD','Dinar iraquí','Irak',replace_SESSION_EMPRESA),
															('IRR','Rial iraní','Irán',replace_SESSION_EMPRESA),
															('ISK','Corona islandesa','Islandia',replace_SESSION_EMPRESA),
															('JMD','Dólar jamaiquino','Jamaica',replace_SESSION_EMPRESA),
															('JOD','Dinar jordano','Jordania',replace_SESSION_EMPRESA),
															('JPY','Yen','Japón',replace_SESSION_EMPRESA),
															('KES','Chelín keniano','Kenia',replace_SESSION_EMPRESA),
															('KGS','Som','Kirguistán',replace_SESSION_EMPRESA),
															('KHR','Riel','Camboya',replace_SESSION_EMPRESA),
															('KMF','Franco comorense','Comoras',replace_SESSION_EMPRESA),
															('KPW','Won norcoreano','Corea del Norte',replace_SESSION_EMPRESA),
															('KRW','Won','Corea del Sur',replace_SESSION_EMPRESA),
															('KWD','Dinar kuwaití','Kuwait',replace_SESSION_EMPRESA),
															('KYD','Dólar de las Islas Caimán','Islas Caimán',replace_SESSION_EMPRESA),
															('KZT','Tenge','Kazajistán',replace_SESSION_EMPRESA),
															('LAK','Kip','Laos',replace_SESSION_EMPRESA),
															('LBP','Libra libanesa','Líbano',replace_SESSION_EMPRESA),
															('LKR','Rupia de Sri Lanka','Sri Lanka',replace_SESSION_EMPRESA),
															('LRD','Dólar liberiano','Liberia',replace_SESSION_EMPRESA),
															('LSL','Loti','Lesoto',replace_SESSION_EMPRESA),
															('LYD','Dinar libio','Libia',replace_SESSION_EMPRESA),
															('MAD','Dírham marroquí','Marruecos, República Árabe Saharaui Democrática',replace_SESSION_EMPRESA),
															('MDL','Leu moldavo','Moldavia',replace_SESSION_EMPRESA),
															('MGA','Ariary malgache','Madagascar',replace_SESSION_EMPRESA),
															('MKD','Denar','Macedonia',replace_SESSION_EMPRESA),
															('MMK','Kyat','Myanmar',replace_SESSION_EMPRESA),
															('MNT','Tugrik','Mongolia',replace_SESSION_EMPRESA),
															('MOP','Pataca','Macao',replace_SESSION_EMPRESA),
															('MRO','Uguiya','Mauritania',replace_SESSION_EMPRESA),
															('MUR','Rupia de Mauricio','Mauricio',replace_SESSION_EMPRESA),
															('MVR','Rufiyaa','Maldivas',replace_SESSION_EMPRESA),
															('MWK','Kwacha','Malaui',replace_SESSION_EMPRESA),
															('MXN','Peso mexicano','México',replace_SESSION_EMPRESA),
															('MXV','Unidad de Inversión (UDI) mexicana','México',replace_SESSION_EMPRESA),
															('MYR','Ringgit malayo','Malasia',replace_SESSION_EMPRESA),
															('MZN','Metical mozambiqueño','Mozambique',replace_SESSION_EMPRESA),
															('NAD','Dólar namibio','Namibia',replace_SESSION_EMPRESA),
															('NGN','Naira','Nigeria',replace_SESSION_EMPRESA),
															('NIO','Córdoba','Nicaragua',replace_SESSION_EMPRESA),
															('NOK','Corona noruega','Isla Bouvet, Noruega, Svalbard y Jan Mayen',replace_SESSION_EMPRESA),
															('NPR','Rupia nepalí','Nepal',replace_SESSION_EMPRESA),
															('NZD','Dólar neozelandés','Islas Cook, Islas Pitcairn, Niue, Nueva Zelanda, Tokelau',replace_SESSION_EMPRESA),
															('OMR','Rial omaní','Omán',replace_SESSION_EMPRESA),
															('PAB','Balboa','Panamá',replace_SESSION_EMPRESA),
															('PEN','Sol','Perú',replace_SESSION_EMPRESA),
															('PGK','Kina','Papúa Nueva Guinea',replace_SESSION_EMPRESA),
															('PHP','Peso filipino','Filipinas',replace_SESSION_EMPRESA),
															('PKR','Rupia pakistaní','Pakistán',replace_SESSION_EMPRESA),
															('PLN','Złoty','Polonia',replace_SESSION_EMPRESA),
															('PYG','Guaraní','Paraguay',replace_SESSION_EMPRESA),
															('QAR','Riyal qatarí','Catar',replace_SESSION_EMPRESA),
															('RON','Leu rumano','Rumania',replace_SESSION_EMPRESA),
															('RSD','Dinar serbio','Serbia',replace_SESSION_EMPRESA),
															('RUB','Rublo ruso','Rusia',replace_SESSION_EMPRESA),
															('RWF','Franco ruandés','Ruanda',replace_SESSION_EMPRESA),
															('SAR','Riyal saudí','Arabia Saudita',replace_SESSION_EMPRESA),
															('SBD','Dólar de las Islas Salomón','Islas Salomón',replace_SESSION_EMPRESA),
															('SCR','Rupia seychelense','Seychelles',replace_SESSION_EMPRESA),
															('SDG','Dinar sudanés','Sudán',replace_SESSION_EMPRESA),
															('SEK','Corona sueca','Suecia',replace_SESSION_EMPRESA),
															('SGD','Dólar de Singapur','Singapur',replace_SESSION_EMPRESA),
															('SHP','Libra de Santa Elena','Santa Elena, Ascensión y Tristán de Acuña',replace_SESSION_EMPRESA),
															('SLL','Leone','Sierra Leona',replace_SESSION_EMPRESA),
															('SOS','Chelín somalí','Somalia',replace_SESSION_EMPRESA),
															('SRD','Dólar surinamés','Surinam',replace_SESSION_EMPRESA),
															('SSP','Libra sursudanesa','Sudán del Sur',replace_SESSION_EMPRESA),
															('STD','Dobra','Santo Tomé y Príncipe',replace_SESSION_EMPRESA),
															('SVC','Colon Salvadoreño','El Salvador',replace_SESSION_EMPRESA),
															('SYP','Libra siria','Siria',replace_SESSION_EMPRESA),
															('SZL','Lilangeni','Suazilandia',replace_SESSION_EMPRESA),
															('THB','Baht','Tailandia',replace_SESSION_EMPRESA),
															('TJS','Somoni tayiko','Tayikistán',replace_SESSION_EMPRESA),
															('TMT','Manat turcomano','Turkmenistán',replace_SESSION_EMPRESA),
															('TND','Dinar tunecino','Túnez',replace_SESSION_EMPRESA),
															('TOP','Paʻanga','Tonga',replace_SESSION_EMPRESA),
															('TRY','Lira turca','Turquía',replace_SESSION_EMPRESA),
															('TTD','Dólar de Trinidad y Tobago','Trinidad y Tobago',replace_SESSION_EMPRESA),
															('TWD','Nuevo dólar taiwanés','República de China',replace_SESSION_EMPRESA),
															('TZS','Chelín tanzano','Tanzania',replace_SESSION_EMPRESA),
															('UAH','Grivna','Ucrania',replace_SESSION_EMPRESA),
															('UGX','Chelín ugandés','Uganda',replace_SESSION_EMPRESA),
															('USD','Dólar estadounidense','Caribe Neerlandés, Ecuador, El Salvador, Estados Unidos, Guam, Haití, Islas Marianas del Norte, Islas Marshall, Islas Turcas y Caicos, Islas ultramarinas de Estados Unidos, Islas Vírgenes Británicas, Islas Vírgenes de los Estados Unidos, Micronesia, Palaos, Panamá, Puerto Rico, Samoa Americana, Territorio Británico del Océano Índico, Timor Oriental',replace_SESSION_EMPRESA),
															('USN','Dólar estadounidense (Siguiente día)','Estados Unidos',replace_SESSION_EMPRESA),
															('UYI','Peso en Unidades Indexadas (Uruguay)','Uruguay',replace_SESSION_EMPRESA),
															('UYU','Peso uruguayo','Uruguay',replace_SESSION_EMPRESA),
															('UZS','Som uzbeko','Uzbekistán',replace_SESSION_EMPRESA),
															('VEF','Bolívar','Venezuela',replace_SESSION_EMPRESA),
															('VES','Bolívar soberano','Venezuela',replace_SESSION_EMPRESA),
															('VND','Dong vietnamita','Vietnam',replace_SESSION_EMPRESA),
															('VUV','Vatu','Vanuatu',replace_SESSION_EMPRESA),
															('WST','Tala','Samoa',replace_SESSION_EMPRESA),
															('XAF','Franco CFA de África Central','Camerún, Chad, Gabón, Guinea Ecuatorial, República Centroafricana, República del Congo',replace_SESSION_EMPRESA),
															('XAG','Plata (una onza troy)','',replace_SESSION_EMPRESA),
															('XAU','Oro (una onza troy)','',replace_SESSION_EMPRESA),
															('XBA','Unidad compuesta europea (EURCO) (Unidad del mercado de bonos)','',replace_SESSION_EMPRESA),
															('XBB','Unidad Monetaria europea (E.M.U.-6) (Unidad del mercado de bonos)','',replace_SESSION_EMPRESA),
															('XBC','Unidad europea de cuenta 9 (E.U.A.-9) (Unidad del mercado de bonos)','',replace_SESSION_EMPRESA),
															('XBD','Unidad europea de cuenta 17 (E.U.A.-17) (Unidad del mercado de bonos)','',replace_SESSION_EMPRESA),
															('XCD','Dólar del Caribe Oriental','Anguila, Antigua y Barbuda, Dominica, Granada, Montserrat, San Cristóbal y Nieves, San Vicente y las Granadinas, Santa Lucía',replace_SESSION_EMPRESA),
															('XDR','Derechos especiales de giro','Fondo Monetario Internacional',replace_SESSION_EMPRESA),
															('XOF','Franco CFA de África Occidental','Benín, Burkina Faso, Costa de Marfil, Guinea-Bisáu, Malí, Níger, Senegal, Togo',replace_SESSION_EMPRESA),
															('XPD','Paladio (una onza troy)','',replace_SESSION_EMPRESA),
															('XPF','Franco CFP','Nueva Caledonia, Polinesia Francesa, Wallis y Futuna',replace_SESSION_EMPRESA),
															('XPT','Platino (una onza troy)','',replace_SESSION_EMPRESA),
															('XSU','SUCRE','Sistema Unitario de Compensación Regional',replace_SESSION_EMPRESA),
															('XTS','Reservado para pruebas','',replace_SESSION_EMPRESA),
															('XUA','Unidad de cuenta BAD','Banco Africano de Desarrollo',replace_SESSION_EMPRESA),
															('XXX','Sin divisa','',replace_SESSION_EMPRESA),
															('YER','Rial yemení','Yemen',replace_SESSION_EMPRESA),
															('ZAR','Rand','Lesoto, Namibia, Sudáfrica',replace_SESSION_EMPRESA),
															('ZMW','Kwacha zambiano','Zambia',replace_SESSION_EMPRESA),
															('ZWL','Dólar zimbabuense','Zimbabue',replace_SESSION_EMPRESA)";
	$rowStructure["hora_extra_diurna"]=[
									[
										"name"=>"fecha_inicio",
										"label"=>"Fecha inicio",
										"comment"=>"",
										"type"=>"date",
										"options" => "",
									],
									[
										"name"=>"hora_inicio",
										"label"=>"Hora Inicio",
										"comment"=>"",
										"type"=>"time",
										"options" => "",
									],
									[
										"name"=>"fecha_fin",
										"label"=>"Fecha fin",
										"comment"=>"",
										"type"=>"date",
										"options" => "",
									],
									[
										"name"=>"hora_fin",
										"label"=>"Hora fin",
										"comment"=>"",
										"type"=>"time",
										"options" => "",
									],
									[
										"name"=>"cantidad",
										"label"=>"Cantidad",
										"comment"=>"Cantidad de horas extras",
										"type"=>"int",
										"options" => "",
									],
									[
										"name"=>"valor",
										"label"=>"Valor",
										"comment"=>"Valor pagado",
										"type"=>"int",
										"options" => "",
									],
									[
										"name"=>"porcentaje",
										"label"=>"Porcentaje",
										"comment"=>"Porcentaje al cual corresponde el calculo de 1 hora extra deacuerdo al tipo (extra,diurna,nocturna,etc)",
										"type"=>"double",
										"options" => "",
									]
								];

	$rowStructure["hora_extra_nocturna"]                          = $rowStructure["hora_extra_diurna"];
	$rowStructure["hora_recargo_nocturno"]                        = $rowStructure["hora_extra_diurna"];
	$rowStructure["hora_recargo_diario_dominicales_y_festivas"]   = $rowStructure["hora_extra_diurna"];
	$rowStructure["hora_extra_nocturna_dominicales_y_festivas"]   = $rowStructure["hora_extra_diurna"];
	$rowStructure["hora_recargo_nocturno_dominicales_y_festivas"] = $rowStructure["hora_extra_diurna"];

	$rowStructure["cesantias"]=[
									[
										"name"=>"porcentaje",
										"label"=>"Porcentaje",
										"comment"=>"Porcentaje que corresponde al Interes de Cesantia de Ley",
										"type"=>"double",
										"options" => "",
									],
									[
										"name"=>"pago_intereses",
										"label"=>"Pago intereses",
										"comment"=>"Pago de los Intereses de Cesantia otorgada por Ley Valor Pagado por Intereses de Cesantias",
										"type"=>"double",
										"options" => "",
									]
								];

	$rowStructure["incapacidad"]=[
									[
										"name"=>"fecha_inicio",
										"label"=>"Fecha inicio",
										"comment"=>"",
										"type"=>"date",
										"options" => "",
									],
									[
										"name"=>"fecha_fin",
										"label"=>"Fecha fin",
										"comment"=>"",
										"type"=>"date",
										"options" => "",
									],
									[
										"name"=>"tipo",
										"label"=>"Tipo",
										"comment"=>"",
										"type"=>"select",
										"options" => ["1"=>"Comun","2"=>"profesional","3"=>"Laboral"],
									],
								];
	$rowStructure["licencia_maternidad_paternidad"]=[
									[
										"name"=>"fecha_inicio",
										"label"=>"Fecha inicio",
										"comment"=>"",
										"type"=>"date",
										"options" => "",
									],
									[
										"name"=>"fecha_fin",
										"label"=>"Fecha fin",
										"comment"=>"",
										"type"=>"date",
										"options" => "",
									]
								];

	$rowStructure["licencia_remunerada"]    = $rowStructure["licencia_maternidad_paternidad"];
	$rowStructure["licencia_no_remunerada"] = $rowStructure["licencia_maternidad_paternidad"];

	$rowStructure["fondo_solidaridad_pensional"]=[
									[
										"name"=>"porcentaje",
										"label"=>"Porcentaje",
										"comment"=>"Debe corresponder al porcentaje de deducción de fondo de seguridad pensional que paga el trabajador",
										"type"=>"double",
										"options" => "",
									],
									[
										"name"=>"deduccion",
										"label"=>"Deduccion",
										"comment"=>"Todo trabajador que devengue un sueldo que sea igual o superior a 4 salarios mininos, debe aportar un 1% al Fondo de solidaridad pensional",
										"type"=>"double",
										"options" => "",
									],
									[
										"name"=>"porcentaje_fondo_subsistencia",
										"label"=>"Porcentaje fondo Sub.",
										"comment"=>"Se debe colocar el Porcentaje que correspondiente al Fondo de Subsistencia correspondiente",
										"type"=>"double",
										"options" => "",
									],
									[
										"name"=>"deduccion_fondo_subsistencia",
										"label"=>"Deduccion fondo Sub.",
										"comment"=>"Valor Pagado correspondiente a Fondo de Subsistencia por parte del trabajador",
										"type"=>"double",
										"options" => "",
									]
												];

	
	
	// $rowStructure["hora_extra"]=[];
	$arrayTablesData ['nomina_electronica_estructura_conceptos'] = 'INSERT INTO nomina_electronica_estructura_conceptos (nombre,estructura,id_empresa) 
																	VALUES
																	("hora_extra_diurna",\''.json_encode($rowStructure["hora_extra_diurna"]).'\',replace_SESSION_EMPRESA),
																	("hora_extra_nocturna",\''.json_encode($rowStructure["hora_extra_nocturna"]).'\',replace_SESSION_EMPRESA),
																	("hora_recargo_nocturno",\''.json_encode($rowStructure["hora_recargo_nocturno"]).'\',replace_SESSION_EMPRESA),
																	("hora_recargo_diario_dominicales_y_festivas",\''.json_encode($rowStructure["hora_recargo_diario_dominicales_y_festivas"]).'\',replace_SESSION_EMPRESA),
																	("hora_extra_nocturna_dominicales_y_festivas",\''.json_encode($rowStructure["hora_extra_nocturna_dominicales_y_festivas"]).'\',replace_SESSION_EMPRESA),
																	("hora_recargo_nocturno_dominicales_y_festivas",\''.json_encode($rowStructure["hora_recargo_nocturno_dominicales_y_festivas"]).'\',replace_SESSION_EMPRESA),
																	("cesantias",\''.json_encode($rowStructure["cesantias"]).'\',replace_SESSION_EMPRESA),
																	("incapacidad",\''.json_encode($rowStructure["incapacidad"]).'\',replace_SESSION_EMPRESA),
																	("licencia_maternidad_paternidad",\''.json_encode($rowStructure["licencia_maternidad_paternidad"]).'\',replace_SESSION_EMPRESA),
																	("licencia_remunerada",\''.json_encode($rowStructure["licencia_remunerada"]).'\',replace_SESSION_EMPRESA),
																	("licencia_no_remunerada",\''.json_encode($rowStructure["licencia_no_remunerada"]).'\',replace_SESSION_EMPRESA),
																	("fondo_solidaridad_pensional",\''.json_encode($rowStructure["fondo_solidaridad_pensional"]).'\',replace_SESSION_EMPRESA)
																	';
																	


